### ISSUE TITLE
fueature request: check if it's a rest day

### ISSUE THREAD

**Issue by abloch** [hebcal/hebcal#102]
I want to write a script that shouldn't run at rest days (Shabbat and Yom-Tov's)
I'd love if hebcal had a flag that returns whether working today is permitted or not

thanks

**Comment by abloch** [comment]
looks like this could be done by parsing the candle lighting times (which are displayed only for shabat and Yom-Tov) but I wish there was more structured way

**Comment by dsadinoff** [comment]
This is an excellent idea. Adding a bit-wise property to holidays seems really straightforward. 
Not sure whether marking the relevant holidays or filtering directly makes the most sense.

**Comment by abloch** [comment]
actually, the holidays are already bitwise-marked (LIGHT_CANDLES,YOM_TOV_ENDS etc.) so I believe implementing such a feature is not too complicated.
https://github.com/hebcal/hebcal/blob/master/holidays.c#L69

I'll try to do it myself if you find it tp be a good idea and if I'll find the time

**Comment by mjradwin** [comment]
Hi @abloch I am going to take a quick swing at this after YK.

One idea would be for the CLI app to exit silently with zero status if today isn't Shabbat or Chag (yontiff). The CLI would exit with non-zero status if today is Shabbat or Chag.

The app would respect any location-based information passed on the CLI. The `-i` flag would continue to be used to determine if we're in Israel or the Diaspora. And if location were specified either with `-C city` or with latitude/longitude (`-l XX,YY -L XX,YY -z timezone`) then it would consider today a chag if the machine's local time is between Candle-lighting time and Havdalah time.

**Comment by mjradwin** [comment]
Released in hebcal 5.2.0
