### ISSUE TITLE
Translate in french

### ISSUE THREAD

**Issue by SebastienGracia** [hebcal/hebcal#104]
Hello,

i want to use your Api like this 
http://www.hebcal.com/link/?geonameid=2996944&m=50

but how can i the result in french ?

Ty

**Comment by mjradwin** [comment]
If you want to customize the results, use the Shabbat times REST API
instead of our Javascript API.

http://www.hebcal.com/home/197/shabbat-times-rest-api

e.g.

http://www.hebcal.com/shabbat/?cfg=json&geo=geoname&geonameid=2996944&m=50

**Comment by prosgracia** [comment]
ty but how can i have the texbox autocomplete city you use ? (to have geonameid)

**Comment by mjradwin** [comment]
Our typeahead/auto complete example:

https://gist.github.com/mjradwin/d4869c2ccc0496b78228

**Comment by mjradwin** [comment]
If you'd like to contribute French transliterations of event titles (see #115), we would welcome them.

Fork the project, copy `po/he.po` to `po/fr.po` and then edit it in a tool like Poedit, then send us a pull request so we can include your translations in the project.

**Comment by mjradwin** [comment]
This was released in v4.15 and c0a4b6a8e917c45554972966d82e83b2a202f8ab
