### ISSUE TITLE
Joomla integration

### ISSUE THREAD

**Issue by fabricecroize** [hebcal/hebcal#105]
Hi,
I'm working on a website for my communauty, developping with Joomla (http://www.centrehillel.org).
I would like to put on the homepage the date of the day in French and in hebrew calendar (just like that :  16 Juil 2015 | 29 Tamouz 5775 ).
 Is there one of your works that I can use for that ? Do you know a Joomla extension for that ? Thanks for help and congratulation for your work !

Kind regards
fabrice

**Comment by yisraeldov** [comment]
You can do that with plain PHP take a look at 
http://php.net/manual/en/function.jdtojewish.php <http://php.net/manual/en/function.jdtojewish.php>

to get started

**Comment by Scimonster** [comment]
@yisraeldov Man! PHP has built-ins for everything!
