### ISSUE TITLE
Problem With API Data 3 Weeks Ago

### ISSUE THREAD

**Issue by sabonmichal** [hebcal/hebcal#106]
Hi,

Was there any issue with the API data about 3 weeks ago? We wrote a Shabbat/Holiday shopping cart closure module based on the hebcal API but all of a sudden there were lots of reports that cart was closed during the week. We just had the developer check it out but he couldn't find any issues.

Where is the API pulling Shabbat/Holiday times from? 
Is it possible for inaccuracies in the data from time to time?

Thank you and Shabbat Shalom!

**Comment by mjradwin** [comment]
No issues that we are aware of. 

The API serves Jewish calendar events from the Hebcal Unix tool.

Hebcal computes sunset based on an algorithm provided by the U.S. Naval Observatory (USNO). The USNO claims accuracy within 2 minutes except at extreme northern or southern latitudes.

Comparison to local NWS charts for sunrise and sunset (which are cheap and easy to come by) shows that with the double precision calculations, the charts produced by this program are no more than 1 minute removed from those charts in lattitudes lower than 41 degrees. Candle lighting times agree with those on popular calendars also to the 1 minute accuracy.

That said, the USNO algorithm can only approximate the candle-lighting times for your location. If you ever have any doubts about Hebcal’s times, consult your local halachic authority.
