### ISSUE TITLE
leyning for differing traditions

### ISSUE THREAD

**Issue by aydeisen** [hebcal/hebcal#108]
Is it possible to configure HEBCAL, as well as the API, to show differing traditions for leyning?  For example, since Re'eh fell on Shabbat Rosh Chodesh Elul, there are two traditions for the haftarah: One to stay with the seven haftaroth of consolation (which is what HebCal shows), and one to read Haftarah Shabbat Rosh Chodesh for Re'eh, and combine the haftarah for Re'eh with the haftarah for Ki Teitzeh.

Can HebCal be update to incorporate this?

**Comment by mjradwin** [comment]
The `hebcal` app does list parashat haShavuah with the `-s` option, but beyond listing the sedra on Shabbat (e.g. `8/15/2015 Parashat Re'eh`) it does not provide any detail about Haftarah.

The feature you're referring to is provided by the Hebcal.com website, e.g. http://www.hebcal.com/sedrot/reeh#haftarah

To implement the feature you want, please submit a pull request for the `hebcal/dotcom` repo (in particular `hebcal.com/bin/calc_triennial.pl`)
