### ISSUE TITLE
Use Olson zoneinfo database for time zones

### ISSUE THREAD

**Issue by mjradwin** [hebcal/hebcal#112]
Danny, how would you feel about releasing a major incompatible change to Hebcal to replace our sunrise/sunset and timezone/DST code with something that works with Olson zoneinfo database?

For the past couple of years I've been using a [fork](https://github.com/mjradwin/hebcal) of Hebcal on hebcal.com to support better handle global timezones and DST observance. Back in July 2013, I replaced some of the code from `rise.{c,h}` to use PHP's datetime extension. As a side effect, I changed the meaning of the `-z timezone` and `-Z daylight_savings_option` command-line flags. In this forked version, you do `-z Asia/Jerusalem` or `-z America/Chicago` instead of `-z +2 -Z israel` or `-z -6 -Z usa`.

At the time, the PHP code was under a somewhat restrictive PHP license, which I couldn't blend with the GPL-based Hebcal. So rather than contaminate the main Hebcal project, I've just been maintaining a fork.

As part of the upcoming PHP 7 release (tentatively scheduled for this month), the PHP Group is re-licensing all of their C code under the GPL-compatible MIT/X license. This means that we can port PHP's datelib into Hebcal in a GPL-compatible way.

This will introduce an incompatibility with the -z command-line flag, so I'd recommend that we call the release Hebcal 4.0.

If you don't object, just comment here, and I'll assign the issue back to myself.

**Comment by dsadinoff** [comment]
I think this is a great idea.  Offloading as much of the TZ handling as possible is an easy win.

**Comment by mjradwin** [comment]
Great. I'll work on folding the code in sometime in the next week or two.

**Comment by mjradwin** [comment]
Code checked in. Just need to do a few more tests and then I'll deploy a GitHub release.

**Comment by mjradwin** [comment]
Hebcal 4.0.1 released.

**Comment by dsadinoff** [comment]
Okay, I only just finally got a chance to appreciate this delta, along with the cross-compiled version of the Olson db.  Great stuff.     
Of course, this implies two things: 
1) some sort of commitment to re-release every time the Olson db changes (a few times per year at least), and perhaps a new versioning scheme to accommodate it.
2) an amusingly large 4MB source file in the repository.  I doubt that that would have been an option in 1992, mostly due to my filesystem quota at school.

But seriously, I wonder whether executing the cross-compile at build time is an option and if so, desirable.

**Comment by dsadinoff** [comment]
...as it would serve to decouple the hebcal release schedule from that of the olson-db.

**Comment by mjradwin** [comment]
Yes, the 4MB `timezonedb.h` is a bit absurd. It's the approach that PHP takes. It does bloat the git repo and the binary, but it's a bit more portable/predictable/consistent than relying on the user's `/usr/share/zoneinfo` being up-to-date.

I've got no problem with the commitment to push a new timezonedb.h a few times per year. I've been doing this with my private fork for the past 2.5 years. It's not terribly difficult to do given the mechanical nature of the work. It could be possible to even automate it. @derickr maintains a small repo at [derickr/timelib](https://github.com/derickr/timelib) and although I've never used Git's [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) feature, this is indeed already a solved problem.

**Comment by dsadinoff** [comment]
faboo.

**Comment by derickr** [comment]
The repository at https://github.com/derickr/timelib is the canonical repository that PHP's files are synced from. It does receive bug fixes as well. And of course new versions of the timezonedb.h file.
