### ISSUE TITLE
Offer multiple translations/transliterations

### ISSUE THREAD

**Issue by mjradwin** [hebcal/hebcal#115]
We've had several requests over the years to support Hebcal in French and/or Russian.

The right way to do this might be to use GNU gettext and to move the existing translations into `.po` files. Then we could easily support additional translations.

**Comment by mjradwin** [comment]
I spent a couple of hours this morning fighting with autoconf/automake and build/link options on Mac OS X. @dsadinoff, do you know of a good example of a package that uses gettext that isn't itself a GNU application? I could benefit from seeing how others have configured their builds.

**Comment by dsadinoff** [comment]
Not really. I think I used it once.

Git seems like an example of a program that uses gettext and is
well-maintained, and isn't a GNU application, although it's GPL'd
https://github.com/git/git/blob/master/Makefile




———
Danny Sadinoff
danny@sadinoff.com

**Comment by dsadinoff** [comment]
They don't seem to use automake.  I can't keep the complex
automake/autoconf/libtool/whatever food web in my head for more than ten
minutes, so maybe we don't need automake.

thought maybe this guy would answer all my questions
https://autotools.io/index.html
but it didn't.


———
Danny Sadinoff
danny@sadinoff.com

**Comment by mjradwin** [comment]
Well, I've made a bunch of progress on getting gettext to work with Hebcal on Linux. But it's turning out to be much less elegant than I had hoped:

1. GNU gettext won't work with message catalogs relative to the current working directory, so you have to do `sudo make install` to get the compiled `hebcal.mo` catalogs copied to `/usr/local/share/locale`. 
2. GNU gettext only wants to work with "real" locale names, so I had to resort to using a real locale (`en_CA.utf8`) to do the Ashkenazi transliterations.
3. gettext is a no-op on Mac OS X and I haven't figured out how to make it actually use `libintl`. I believe it's possible to make it work somehow (WordPress uses gettext, and it apparently runs on Mac inside of an application called MAMP just fine). But it doesn't work out of the box with autoconf.

None of these are show-stoppers yet, but I'm not feeling a lot of love from the supposedly best possible library for l10n on the planet.

**Comment by mjradwin** [comment]
Still haven't gotten gettext to play nicely on Mac (or FreeBSD), but I'm not ready to give up on this feature. @ariedov has already forked Hebcal and has started working on Russian transliteration, and someone just pinged me to volunteer to work on Polish transliteration. So there's clearly merit in this approach!

I've fixed the first issue above. The code is working correctly on Linux (tested both Ubuntu and CentOS myself). I've updated the `.travis.yml` to use `./configure --prefix=/tmp/hebcal && make all install check` and it's working even without sudo, which is great.

Items 2 and 3 above are still unfixed, but perhaps that might be OK? We could either drop Mac/FreeBSD support altogether, or we could use the presence/absence of the `ENABLE_NLS` macro to disable features that would no longer work without gettext:

* `-8` Hebrew
* `-a` Askhenazi transliterations
* `--locale` (new feature)

@dsadinoff what do you think? Merge this to master?

**Comment by Scimonster** [comment]
I haven't looked at the code, but might it be worth creating a simple
function to just parse a language file from any code? It's not really so
complex...

On Saturday, January 9, 2016, Michael J. Radwin <notifications@github.com>
wrote:

> Still haven't gotten gettext to play nicely on Mac (or FreeBSD), but I'm
> not ready to give up on this feature. @ariedov
> <https://github.com/ariedov> has already forked Hebcal and has started
> working on Russian transliteration, and someone just pinged me to volunteer
> to work on Polish transliteration. So there's clearly merit in this
> approach!
>
> I've fixed the first issue above. The code is working correctly on Linux
> (tested both Ubuntu and CentOS myself). I've updated the .travis.yml to
> use ./configure --prefix=/tmp/hebcal && make all install check and it's
> working even without sudo, which is great.
>
> Items 2 and 3 above are still unfixed, but perhaps that might be OK? We
> could either drop Mac/FreeBSD support altogether, or we could use the
> presence/absence of the ENABLE_NLS macro to disable features that would
> no longer work without gettext:
>
>    - -8 Hebrew
>    - -a Askhenazi transliterations
>    - --locale (new feature)
>
> @dsadinoff <https://github.com/dsadinoff> what do you think? Merge this
> to master?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hebcal/hebcal/issues/115#issuecomment-170168952>.
>


-- 
Sent from Gmail Mobile

**Comment by mjradwin** [comment]
@Scimonster, yes, we could statically compile the `.po` files directly into string tables in the executable to avoid gettext library issues. A little helper Perl or Python script as part of the build process would make this easy to do. Depending on Perl/Python might reduce portability a little bit... but given that gettext also seems to reduce portability it might be the better of two evils.

Because it's working "well enough" on Linux, I'm inclined to move this work forward to `master` (just merged the branch) and let it soak there for a bit and start to get some value out of it (e.g. adding Russian translation to hebcal.com for users who have been asking for it).

**Comment by mjradwin** [comment]
Declaring this finished. Will be included in hebcal 4.3.

**Comment by sjpotter** [comment]
I just did a checkout and build and "-a/--ashekanis"  doesn't do anything i.e. get Sukkot instead of Sukkos (and hence test fails)

**Comment by mjradwin** [comment]
Did you do "sudo make install" as well? The new version requires gettext message catalogues to be installed in the correct directory to work.

**Comment by sjpotter** [comment]
yes, but this is the tests that I'm talking about, shouldn't need to be installed for that....

**Comment by mjradwin** [comment]
Actually yes you do need to install .mo files for tests to pass. This is a limitation of gettext. It's a very inconvenient thing. So much so that I was tempted to get rid of gettext and just include a perl script to compile the .po translations into big static C arrays before publishing a hebcal 4.3 release. But I haven't had the time to do that...

Take a look at .travis.yml and you will see a formula for getting the code built and installed in /tmp in a way that will cause automated tests to pass.

**Comment by sjpotter** [comment]
ok, just thinking ahead for the debian package, updating the debian package to 4.1, that's relatively easy.

**Comment by mjradwin** [comment]
If you are packaging for Debian, 4.0.2 is our most recent stable release. 4.1 is stable except the experimental zmanim feature.

**Comment by mjradwin** [comment]
OK, I've had it with gettext. I nuked it and replaced with a Perl script that builds static string tables from the `.po` files. Translators can still use good tools like Poedit, but at runtime we don't have any dependency on gettext message catalogues.

Closing this feature request for real now.
