### ISSUE TITLE
Need better options parsing

### ISSUE THREAD

**Issue by dsadinoff** [hebcal/hebcal#117]
Proposed: we upgrade to a decent options module, e.g. cargo
https://github.com/JoakimSoderberg/cargo

**Comment by mjradwin** [comment]
I made some guesses as to what to name various longopts. We could easily rename them or even remove them (cargo will work correctly even if you only specify short single-dash option names).

Do you have preferences for better long option names? 

```Usage: hebcal [--ashkenazis] [--candlelighting] [--city CITY]
              [--candle-mins CANDLE-MINS] [--havdalah-mins HAVDALAH-MINS]
              [--latitude LATITUDE] [--longitude LONGITUDE] [--dates-all]
              [--dates-some] [--infile INFILE] [--euro-dates]
              [--twenty-four-hour] [--format FORMAT] [--dafyomi]
              [--no-holidays] [--hebrew-date] [--israeli] [--molad] [--omer]
              [--sunriseset] [--tabs] [--sedrot] [--daily-sedra] [--today]
              [--today-nogreg] [--weekday] [--abbreviated] [--year-abbrev]
              [--yahrtzeit YAHRTZEIT] [--no-rosh-chodesh]
              [--timezone TIMEZONE] [--zmanim] [--help] [--version]


Options:
    -a, --ashkenazis                   Use ashkenazis Hebrew
    -d, --dates-all                    Print the Hebrew date for the entire date
                                       range
    -D, --dates-some                   Print the Hebrew date for dates with some
                                       event
    -I, --infile INFILE                Get non-yahrtzeit Hebrew user events from
                                       specified file. The format is: mmm dd
                                       string, Where mmm is a Hebrew month name
    -e, --euro-dates                   Ouput 'European' dates -- DD.MM.YYYY
                                       format
    -E, --twenty-four-hour             Ouput 24-hour times (e.g. 18:37 instead
                                       of 6:37)
    -f, --format FORMAT                change output to FORMAT
    -F, --dafyomi                      Output the Daf Yomi for the entire date
                                       range
    -h, --no-holidays                  Suppress default holidays
    -H, --hebrew-date                  Use Hebrew date ranges - only needed when
                                       e.g. hebcal -H 5373
    -i, --israeli                      Israeli holiday and sedra schedule
    -M, --molad                        Print the molad on Shabbat Mevorchim
    -o, --omer                         Add days of the Omer
    -O, --sunriseset                   Output sunrise and sunset times every day
    -r, --tabs                         Tab delineated format
    -s, --sedrot                       Add weekly sedrot on Saturday
    -S, --daily-sedra                  Print sedrah of the week on all calendar
                                       days
    -t, --today                        Only output for today's date
    -T, --today-nogreg                 Print today's pertinent information, no
                                       gregorian date
    -w, --weekday                      Add day of the week
    -W, --abbreviated                  Weekly view. Omer, dafyomi, and
                                       non-date-specific zemanim are shown once
                                       a week, on the day which corresponds to
                                       the first day in the range.
    -y, --year-abbrev                  Print only last two digits of year
    -Y, --yahrtzeit YAHRTZEIT          Get yahrtzeit dates from specified file.
                                       The format is: mm dd yyyy string the
                                       first three fields specify a *Gregorian*
                                       date.
    -x, --no-rosh-chodesh              Suppress Rosh Chodesh
    --help                             Show this help
    --version                          Show version number

Candle lighting:
  Options related to candle-lighting times.

    -c, --candlelighting               Print candlelighting times
    -C, --city CITY                    City for candle-lighting
    -b, --candle-mins CANDLE-MINS      Set candle-lighting to occur this many
                                       minutes before sundown
    -m, --havdalah-mins HAVDALAH-MINS  Set Havdalah to occur this many minutes
                                       after sundown
    -l, --latitude LATITUDE            Set the latitude for solar calculations
                                       to xx degrees and yy minutes. Negative
                                       values are south
    -L, --longitude LONGITUDE          Set the longitude for solar calculations
                                       to xx degrees and yy minutes. Negative
                                       values are EAST. The -l and -L switches
                                       must both be used, or not at all. These
                                       switches override the -C (localize to
                                       city) switch
    -z, --timezone TIMEZONE            Use specified timezone, overriding the -C
                                       (localize to city) switch
    -Z, --zmanim                       Print zemanim (experimental)
```

**Comment by dsadinoff** [comment]
for -D I would go with --hebrew-date-for-event  or maybe
--hebrew-dates-for-events

I seem to have missed the delta for -W.  clever.

I think --sunriseset should be  --display-sun-times or --sun-rise-and-set.
   Long options should embrace the long, and be explicit about what they
do.  (shorter aliases are okay too, but smushing words together seems like
a style error to me).

———
Danny Sadinoff
danny@sadinoff.com

On Mon, Dec 28, 2015 at 7:22 PM, Michael J. Radwin <notifications@github.com

**Comment by dsadinoff** [comment]
--daf-yomi

———
Danny Sadinoff
danny@sadinoff.com

**Comment by mjradwin** [comment]
Uh oh, looks like cargo can't handle short options bundled together. For example, if you wanted to use `hebcal -ho` to print out the days of the Omer for the current year, you'd have to specify it as `hebcal -h -o` instead.

If you try invoking `hebcal -ho` you'll get this error:

```
    Unknown options:
    -ho 
    ~~~
    -ho  (Did you mean -h)?
```

Here's an excerpt from their code that suggests that in fact short-option bundling isn't yet supported:

https://github.com/JoakimSoderberg/cargo/blob/master/cargo.c#L1542

```
            // TODO: This could be more general to support
            //       short command lines bundled together:
            //       "-vaet" same as "-v -a -e -t"...
```

So the code, as it is, breaks compatibility with previous versions. That may be OK, because we've already broken backwards compatibility some things in version 4 (such as changing the meaning of `-z` and `-Z` flags).

Or, if it's a big enough breakage, do you think we should go back to using `getopt_long()` or some other (less-awesome) options parser? 

Or should I file a feature request on the cargo project? Don't know if I understand their implementation well enough to do it myself.

**Comment by dsadinoff** [comment]
Argh. And here it showed such promise. We might be able to profitably
pre-process the command line as a workaround. ( obviously this ought to
happen inside cargo but life's too short. I'd log a feature request and
forget it. )

Seems like a simple transform, no? Am I missing something?

On Monday, 28 December 2015, Michael J. Radwin <notifications@github.com>
wrote:

> Uh oh, looks like cargo can't handle short options bundled together. For
> example, if you wanted to use hebcal -ho to print out the days of the
> Omer for the current year, you'd have to specify it as hebcal -h -o
> instead.
>
> If you try invoking hebcal -ho you'll get this error:
>
>     Unknown options:
>     -ho
>     ~~~
>     -ho  (Did you mean -h)?
>
> Here's an excerpt from their code that suggests that in fact short-option
> bundling isn't yet supported:
>
> https://github.com/JoakimSoderberg/cargo/blob/master/cargo.c#L1542
>
>             // TODO: This could be more general to support
>             //       short command lines bundled together:
>             //       "-vaet" same as "-v -a -e -t"...
>
> So the code, as it is, breaks compatibility with previous versions. That
> may be OK, because we've already broken backwards compatibility some things
> in version 4 (such as changing the meaning of -z and -Z flags).
>
> Or, if it's a big enough breakage, do you think we should go back to using
> getopt_long() or some other (less-awesome) options parser?
>
> Or should I file a feature request on the cargo project? Don't know if I
> understand their implementation well enough to do it myself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hebcal/hebcal/issues/117#issuecomment-167664952>.
>


-- 
———
Danny Sadinoff
danny@sadinoff.com

**Comment by dsadinoff** [comment]
I would rather preserve cli reverse-compatibility.

On Monday, 28 December 2015, Michael J. Radwin <notifications@github.com>
wrote:

> Uh oh, looks like cargo can't handle short options bundled together. For
> example, if you wanted to use hebcal -ho to print out the days of the
> Omer for the current year, you'd have to specify it as hebcal -h -o
> instead.
>
> If you try invoking hebcal -ho you'll get this error:
>
>     Unknown options:
>     -ho
>     ~~~
>     -ho  (Did you mean -h)?
>
> Here's an excerpt from their code that suggests that in fact short-option
> bundling isn't yet supported:
>
> https://github.com/JoakimSoderberg/cargo/blob/master/cargo.c#L1542
>
>             // TODO: This could be more general to support
>             //       short command lines bundled together:
>             //       "-vaet" same as "-v -a -e -t"...
>
> So the code, as it is, breaks compatibility with previous versions. That
> may be OK, because we've already broken backwards compatibility some things
> in version 4 (such as changing the meaning of -z and -Z flags).
>
> Or, if it's a big enough breakage, do you think we should go back to using
> getopt_long() or some other (less-awesome) options parser?
>
> Or should I file a feature request on the cargo project? Don't know if I
> understand their implementation well enough to do it myself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hebcal/hebcal/issues/117#issuecomment-167664952>.
>


-- 
———
Danny Sadinoff
danny@sadinoff.com

**Comment by mjradwin** [comment]
Logged a feature request. Should be possible to workaround this with pre-processing. Just a matter of writing more code. Sigh.

**Comment by mjradwin** [comment]
I'm going to revert (mostly) back to what we were doing before, with the minor change to use GNU getopt_long instead of your ancient AT&T getopt implementation. That will still enable us to use both short and long options (adding the --help and --verbose flags), and will preserve CLI compatibility. We'll have to go back to the hand-crafted help message, which is too bad.

I'll try to leave the cargo stuff in there inside of a big #ifdef block in case they get around to implementing the options bundling feature at some point in the future. The cargo author did get back to me thanking me for the feature request, but didn't promise any timeline to implement the change.

Pre-processing the input to handle cargo's deficiency is just too much work, and I'd rather spend time on a more user-visible feature such as the gettext stuff to enable French/Russian/etc translations.

**Comment by dsadinoff** [comment]
I endorse your prioritization.

On Tuesday, 29 December 2015, Michael J. Radwin <notifications@github.com>
wrote:

> I'm going to revert (mostly) back to what we were doing before, with the
> minor change to use GNU getopt_long instead of your ancient AT&T getopt
> implementation. That will still enable us to use both short and long
> options (adding the --help and --verbose flags), and will preserve CLI
> compatibility. We'll have to go back to the hand-crafted help message,
> which is too bad.
>
> I'll try to leave the cargo stuff in there inside of a big #ifdef block in
> case they get around to implementing the options bundling feature at some
> point in the future. The cargo author did get back to me thanking me for
> the feature request, but didn't promise any timeline to implement the
> change.
>
> Pre-processing the input to handle cargo's deficiency is just too much
> work, and I'd rather spend time on a more user-visible feature such as the
> gettext stuff to enable French/Russian/etc translations.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hebcal/hebcal/issues/117#issuecomment-167847256>.
>


-- 
———
Danny Sadinoff
danny@sadinoff.com

**Comment by mjradwin** [comment]
Closing this for now. getopt_long is a minor improvement, actually (we now have `--help`, `--version`, and alternate long option names).

We'll re-evaluate cargo if and when the options bundling feature is added.
