### ISSUE TITLE
Calendar converter

### ISSUE THREAD

**Issue by CalendarGuy** [hebcal/hebcal#118]
Your date converter makes a ridiculous loop in the years 5855 (Hebrew calendar) and 2095 (Gregorian calendar)

29th of Adar II, 5855 = Mon, 4 April 2095
1st of Nisan, 5855 = Tue, 5 April 2095

I think it also happens with the previous and following years... Maybe it is not prepared to work with numbers above 2016 but I need dates in the future because this is for fiction that uses the Hebrew calendar. Please... Could you correct the flaw? I've used it for other dates around that range (From somewhere in Gregorian calendar's 2077 to... Well, in the Hebrew calendar it would be anywhere in the year 5854).

**Comment by Scimonster** [comment]
What's wrong with the dates you posted?

On Saturday, January 2, 2016, CalendarGuy <notifications@github.com> wrote:

> Your hate converter makes a ridiculous loop in the years 5855 (Hebrew
> calendar) and 2095 (Gregorian calendar)
>
> 29th of Adar II, 5855 = Mon, 4 April 2095
> 1st of Nisan, 5855 = Tue, 5 April 2095
>
> I think it also happens with the previous and following years Maybe it is
> not prepared to work with numbers above 2016 but I need dates in the future
> because this is for fiction that uses the Hebrew calendar Please Could you
> correct the flaw? I've used it for other dates around that range (From
> somewhere in Gregorian calendar's 2077 to Well, in the Hebrew calendar it
> would be anywhere in the year 5854)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hebcal/hebcal/issues/118>.
>


-- 
Sent from Gmail Mobile

**Comment by CalendarGuy** [comment]
The last day of the year 5855 is, in the Gregorian calendar, located before the first day of that same year? Or I am wrong with my understanding of how the Hebrew months are ordered?

**Comment by Scimonster** [comment]
It's a bit confusing. The year number changes at the beginning of Tishrei,
even though biblically Nisan is the first month.

On Saturday, January 2, 2016, CalendarGuy <notifications@github.com> wrote:

> The last day of the year 5855 is, in the Gregorian calendar, located
> before the first day of that same year? Or I am wrong with my understanding
> of how the Hebrew months are ordered?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hebcal/hebcal/issues/118#issuecomment-168408521>.
>


-- 
Sent from Gmail Mobile

**Comment by CalendarGuy** [comment]
Now I am wondering which is wrong then, the calendar or me... I guess I cannot benefit from the converter... I need an outright table to see date by date how one compares to the other.

**Comment by Scimonster** [comment]
Since the calendar is right, it must be you. :)
I'm on mobile right now, but if you go to hebcal.com it lets you generate a
calendar for a whole year.

On Saturday, January 2, 2016, CalendarGuy <notifications@github.com> wrote:

> Now I am wondering which is wrong then, the calendar or me... I guess I
> cannot benefit from the converter... I need an outright table to see date
> by date how one compares to the other.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hebcal/hebcal/issues/118#issuecomment-168411148>.
>


-- 
Sent from Gmail Mobile

**Comment by dsadinoff** [comment]
Hebcal may be ridiculous, but not because of this. Good luck with your fiction!

Not a bug.

**Comment by CalendarGuy** [comment]
Thanks! :D .
