### ISSUE TITLE
does the --format option work?

### ISSUE THREAD

**Issue by aliber4079** [hebcal/hebcal#123]
trying it on the command line and then looking at the code it looks like it is not wired in yet?

thanks,

**Comment by mjradwin** [comment]
According to `git blame`, it's been disabled for more than a decade.

https://github.com/hebcal/hebcal/blob/master/hebcal.c#L498

```
65b4b6c9 c/hebcal.c (sadinoff          2004-02-25 04:48:54 +0000 498) /*              char buf[200];
65b4b6c9 c/hebcal.c (sadinoff          2004-02-25 04:48:54 +0000 499)               puts(formatLine( todayGreg, todayHeb, holip->name, buf, 200));
65b4b6c9 c/hebcal.c (sadinoff          2004-02-25 04:48:54 +0000 500) */
```

It's dead code. Instead of fixing it, perhaps we should remove the option?

**Comment by mjradwin** [comment]
Removed the dead code and the references from documentation.
