### ISSUE TITLE
unix at

### ISSUE THREAD

**Issue by mankowitz** [hebcal/hebcal#124]
suppose I want to use hebcal for home automation and I want to flash the lights on erev shabbat. What is the best way of doing this? Can hebcal be linked to the unix "at" command?

**Comment by roidayan** [comment]
nice idea.

you can use crontab to run a script every 5 minutes on friday and the script will check shabbat time with hebcal and flash the lights if it's in time range such as it will only do the action once.

**Comment by mjradwin** [comment]
You could do something like this

```
lighting_times=`hebcal -x -h -c -E -e | perl -ne 'if (/^(\d+)\.(\d+)\.(\d+)\s+Candle lighting:\s+(\d+):(\d+)/) { print sprintf("%04d%02d%02d%02d%02d\n", $3, $2, $1, $4, $5); }'`

for tm in $lighting_times; do echo "hello" | at -t $tm; done
```

The first line runs `hebcal` for an entire year and collects a set of timestamps in POSIX time format (like `201601011621 201601081627 201601151635`). The second line iterates over the list of timestamps and runs the `at` command with `-t` option for each timestamp.
