### ISSUE TITLE
Full Moons?

### ISSUE THREAD

**Issue by ora68** [hebcal/hebcal#127]
I hope this isn't a dumb question.  I noticed that Rosh Chodesh Nisan seems to be on or near a full moon rather that a new moon prior to 1924.  Why would that be?

**Comment by dsadinoff** [comment]
I think the premise is unsound:

```
$ ./hebcal --years 10 1914|grep Nisan
3/28/1914 Rosh Chodesh Nisan
3/16/1915 Rosh Chodesh Nisan
4/4/1916 Rosh Chodesh Nisan
3/24/1917 Rosh Chodesh Nisan
3/14/1918 Rosh Chodesh Nisan
4/1/1919 Rosh Chodesh Nisan
3/20/1920 Rosh Chodesh Nisan
4/9/1921 Rosh Chodesh Nisan
3/30/1922 Rosh Chodesh Nisan
3/18/1923 Rosh Chodesh Nisan

```
phases according to moonpage.com: 
e.g. 
http://www.moonpage.com/index.html?go=T&auto_dst=T&tzone=ut&m=3&d=28&y=1914&hour=0&min=0&sec=0


```
3/28/1914 1.41%
3/16/1915  NEW
4/4/1916 1.97%
3/24/1917 0.99%
3/14/1918 2.13%
4/1/1919  NEW
3/20/1920 NEW
4/9/1921 NEW
3/30/1922 1.98%
3/18/1923 NEW

```

Are you sure you weren't looking at Passover?

**Comment by ora68** [comment]
The problem was at "www.TimeAndDate.com" that I was using to read phase 
of the moon.  They don't have them right before 1924.  Sorry to have 
bothered you.

**Comment by dsadinoff** [comment]
a two-week error like that is almost certainly due to a Julian/Gregorian calendar thing.  

Hebcal's is a purely gregorian (what's called a Proleptic Gregorian) calendar, so this would be consistent with Timeanddate.com switching to the Julian calendar in 1923.  Many european countries changed over in either the 16th or 18th centuries.  The Russian and Ottoman empires changed later.

**Comment by ora68** [comment]
I did a bunch of work a year ago using FullCalendar.js and three solid 
years of heavy duty astronomy right before that.  It was contract work 
for a professor at a Bible college in Vitginia.  The man tells me that 
he also went through all the studies to be ordained as a Jewish rabbi.  
My background is forty years of engineering, so he hired me because I 
knew enough calculus and physics to understand the math that lead 
astronomers at the NASA JPL and United States Naval Observatory were 
doing.  This time he asked me if I could make a Jewish calendar for 
him.  His opinion is that Christianity is essentially one of many 
variants of Judaism and wants to show that Jesus himself spent his whole 
life as an observant Jew and kept all the required feasts.  I told him I 
would try to learn what was needed.  It took about three Google searches 
to hit HebCal and I told him, I think this is what you need.  Two more 
Google searches landed me at Chabad.org and it looked like the right 
stuff also.

The give-away about TimeAndDate.com was about two hours after I asked 
the first question.  I saw that they had a new moon on March 4, 1923 and 
a new moon on March 5, 1924 so I wrote them telling them that this is 
not possible.

Now it is about three weeks into the project and I have read more than a 
hundred web sites made by more than a hundred different rabbis.  My wife 
was born a Sephardic Jew from Alexandria, Egypt and she said to me, 
"That's typical.  You can ask my cousin Josiah in Israel.  You just 
cannot place any two Jews in the same room at the same time without 
getting some irreconcilable difference about some point of the Law."  I 
told her I just need to be able to tell Dr. Dale when the correct times 
for the feasts are.  I am going to tell Dr. Dale that HebCal is the 
authority because it agrees with what I read in Leviticus and 
Chabad.org.  I spent a couple of days checking all dates in the 20th 
Century against the JPL's calculations of new moons and it is clear to 
me that TimeAndDate.com has a defect in their algorithm.  I even cross 
checked against ICOP (International Crescent Observation Project) in 
UAR, who has hundreds of people going out every night to look at the sky 
and report what they saw.  I even carefully read the writings of Hillel 
II and Maimonides to learn what their algorithms are.

I guess that I really should take the time to learn to read the Hebrew 
language.  No big problem.  I am already fluent in Latin and Greek and 
somewhat passable in Arabic.

**Comment by dsadinoff** [comment]
Verified timeanddate has a julian -> gregorian changeover in 1923.  They're not wrong, just using a different calendar.

http://www.timeanddate.com/moon/phases/?year=1923

**Comment by dsadinoff** [comment]
![local times](https://cloud.githubusercontent.com/assets/287416/15451462/0eddacd4-1fcc-11e6-82bc-b7661752ff58.png)
