### ISSUE TITLE
BUG, this week the "havdala" time return as "candles"

### ISSUE THREAD

**Issue by GuyAssaf** [hebcal/hebcal#131]
In this link: http://www.hebcal.com/shabbat/?cfg=json&geonameid=281184&m=50

look for category: candles, it's appear twice.

**Comment by mjradwin** [comment]
Not a bug. It's candle lighting time for the beginning of Shavuot

**Comment by GuyAssaf** [comment]
My problem was that there is no "Havdala" time.
Is it not something I can trust on ?

I will need to get Candles lightning time and havdla time every week, should I trust on the "category" field ?

**Comment by mjradwin** [comment]
When Shabbat goes immediately into Yom Tov, you will not see "candles" followed by "havdalah". Instead you will see "candles" followed by "candles".
