### ISSUE TITLE
GeoNames as a location provider

### ISSUE THREAD

**Issue by kkowalsky** [hebcal/hebcal#135]
I was wondering if you had considered using other sources for location data besides GeoNames? It can be a mess to deal with, as compared to [Who's On First](https://whosonfirst.mapzen.com/spelunker/placetypes/)?

**Comment by mjradwin** [comment]
The hebcal/hebcal project doesn't use geonames or any location provider. It
only uses latitude, longitude, and tzid such as Europe/Paris.

The hebcal/dotcom project does use geonames and we are quite happy with it
there. The data is imperfect but good enough for our needs, the licensing
is great, and most importantly all users who have calendar subscriptions
are depending on stable city IDs. So even if we needed to adopt a new
location provider for some reason, we would have to maintain a mapping from
the geoname ID space to the new ID space.

**Comment by kkowalsky** [comment]
Thanks for the response @mjradwin!
