### ISSUE TITLE
Include dawn in zmanim output?

### ISSUE THREAD

**Issue by jikamens** [hebcal/hebcal#137]
It looks like the output of `hebcal -Z` includes sunrise but not dawn. Both are significant, e.g., I believe minor fasts start at dawn, and I think you can count the omer with a bracha up until dawn? Therefore, it would be nice if the zmanim output included dawn.

**Comment by mjradwin** [comment]
This is fixed in hebcal 5.0.4

* Add additional halachic times when `-Z` (zemanim) is specifed:
  - Alot haShachar
  - Misheyakir
  - Misheyakir Machmir
  - Dawn (#137)
  - Kriat Shema, sof zeman (MGA)
  - Tefilah, sof zeman (MGA)
  - Dusk
