### ISSUE TITLE
City in West Bank getting two-day yom tov

### ISSUE THREAD

**Issue by ronitslyper** [hebcal/hebcal#141]
Awesome api.

This is my query for the location of Karnei Shomron:
https://www.hebcal.com/hebcal/?v=1&cfg=json&maj=on&min=off&mod=off&nx=on&year=now&month=x&ss=off&mf=off&c=on&m=50&s=off&geo=pos&latitude=32.172&longitude=35.097&tzid=Asia/Hebron

E.g. items[138] incorrectly returns Friday as being Simchat Torah. Quick scan looks like it's getting two-day yom tov's on the other relevant holidays too.

**Comment by Scimonster** [comment]
You need to specify `i=on` to use Israeli yom tov schedule.

See https://www.hebcal.com/home/195/jewish-calendar-rest-api
