### ISSUE TITLE
Suggested improvement

### ISSUE THREAD

**Issue by mumof9** [hebcal/hebcal#142]
Could you please update the hebcal with the ability to set alerts within our iphone/ipad calenders? I need a audio reminder for lighting Shabbat & Havdalah candles, etc....

**Comment by mjradwin** [comment]
The iOS 8 Calendar app now allows you to turn on/off notifications on a per-calendar basis. To do this, simply go into the Calendar app, tap the “Calendars” button in the bottom center to bring up your list of Calendars, and then tap the red “i” to the left of the calendar you’d like to change. Scrolling all the way to the bottom will reveal an “Event Alerts” option — simply toggle this ON or OFF.

**Comment by mumof9** [comment]
Thank-you for replying. 

I was aware of the feature and process that you described. The problem is that to be able to set an audible alarm via the “alerts” feature within the calendar you have to manually set each and every one for some events. 

For instance, I had no problem setting an actual audible “alert” alarm to go off 10 minutes before I am to light Shabbos candles. Because when I did so for the first Shabbat an option came up allowing me to set this alarm for all future events. However for Havdalah no such feature was programmed into the calendar so I have to manually set an audible alert alarm to remind me that I can begin Havdalah for all 52 Havdalahs. That is an unnecessary, time-consuming, pain☹️

Blessings
~ Laura
