### ISSUE TITLE
Android code for date convertion from hebrew date to gregorian date

### ISSUE THREAD

**Issue by spesate** [hebcal/hebcal#147]
I have develop an app for a simple siddur, and I will like to add a convertion date between Hebrew to Gregorian dates, I have allready a convertion from Gregorian to Hebrew and works fine, but I will live to add de Hebrew to Gregorian date, i have been requested for this feature to app. Can you help?

**Comment by mjradwin** [comment]
If you're looking for Java code for Android, we'd recommend the excellent https://github.com/KosherJava/zmanim which can convert between Gregorian and Hebrew dates.
