### ISSUE TITLE
Ashkenazi Pronunciation & Remove Date

### ISSUE THREAD

**Issue by elifine** [hebcal/hebcal#148]
I would like to use the RSS feed for - **Parashat ha-Shavua RSS (Diaspora) – Torah reading of the week.
http://www.hebcal.com/sedrot/index.xml**. However, I want it with Ashkenazi pronunciation i.e. **not** Parshat Shemot, **Rather** Parshas Shemos.
Also, I don't want it to display the date next to the parsha, just the parsha.
Thank you.

**Comment by chaimleib** [comment]
I submitted PR #234, which may help.

**Comment by mjradwin** [comment]
Thanks for this suggestion. We have added a new RSS feed as follows:

https://www.hebcal.com/sedrot/index-ashkenazi.xml

Further, we have added RSS feeds for all supported languages. You'll find a new dropdown for the RSS feeds at https://www.hebcal.com/sedrot/#download

<img width="791" alt="Screen Shot 2022-06-21 at 1 22 08 PM" src="https://user-images.githubusercontent.com/3769045/174890689-7392687b-3e56-45cc-ad04-bc0b115b7277.png">
