### ISSUE TITLE
Cannot remove hebcal from Google Calendar after downolading it (not subscribing)

### ISSUE THREAD

**Issue by squirrelnutkin** [hebcal/hebcal#150]
I added Hebcal to my google calendar by downloading it. It has now integrated itself into my main calendar and there seems to be no way to delete it without killing off my calendar completely. I CANNOT UNSUBSCRIBE BECAUSE THERE IS NO SEPARATE CALENDAR TO UNSUBSCRIBE FROM. There are numerous posts about this on your support page (2 are mine) not only from Google calendar users but from Outlook and mac users as well. PLEASE RESPECT YOUR USERS AND REPLY TO THESE POSTS AND LET US KNOW HOW TO MAKE THE CALENDAR GO AWAY. It hogs the top two lines of every calendar day and I cannot see my actual appointments.

**Comment by mjradwin** [comment]
Instructions for removing Hebcal from Google Calendar are published here:

https://www.hebcal.com/home/180/gcal-delete-jewish-calendar

If you didn't use the recommended subscription option, and instead followed the [Google Calendar alternative instructions – Jewish holidays download](https://www.hebcal.com/home/59/google-calendar-alternative-instructions) instructions, you can remove your Hebcal calendar using a similar approach to above.

Note that the Google Calendar alternative instructions include this text at the top of the page in a yellow warning box: 

> Please note carefully step 10 and step 15 below. These steps have you create a new, separate calendar to upload your Hebcal events. A separate calendar allows you to assign a different color and notifications to events. If you skip these steps you may inadvertently merge Hebcal events with your own calendar events, and this will make it difficult to remove Hebcal events in the future should you choose to do so.

If unfortunately you skipped the recommended steps, you may have inadvertently merged Hebcal events with your own calendar events. Unfortunately, merging events into your own main calendar is a one-way operation. The only way to remove merged events in Google Calendar is to delete them one-by-one.
