### ISSUE TITLE
Have API send multple dates in POST and returns an array of converted dates

### ISSUE THREAD

**Issue by SammyBerk** [hebcal/hebcal#153]
Hi and thank you for this awesome API!

I use this API to Convert Dates from Gregorian to Hebrew and Hebrew to Gregorian.

https://www.hebcal.com/home/219/hebrew-date-converter-rest-api

Issue is this API can only offer conversion for 1 day at a time so i have to make calls 1 by 1 for all dates that i have.

Is it possible to make an API in which i send multiple dates in POST and it returns an array of converted dates?

This way a lot of calls from app to this API will be optimized

**Comment by mjradwin** [comment]
Hi, we recently added support to convert a batch of Gregorian dates to Hebrew dates.

You can use this URL format:

https://www.hebcal.com/converter?cfg=json&start=2021-12-29&end=2022-01-04&g2h=1

start=2021-12-29 – Gregorian start date in YYYY-MM-DD format
end=2022-01-04 – Gregorian end date in YYYY-MM-DD format
g2h=1 – Convert from Gregorian to Hebrew date
cfg=json – output format is JSON (cfg=json)
