### ISSUE TITLE
Translation in French

### ISSUE THREAD

**Issue by mneiger** [hebcal/hebcal#158]
I would like to contribute to a translation/transliteration in French.
However I'm not familiar with the tools. Please get in touch and I'll do the work.

**Comment by yarons** [comment]
You can download the following file:
https://github.com/hebcal/hebcal/blob/master/po/he.po
Edit it with a PO tools such as Poedit (Works on Linux/Mac/Windows) and upload it back here, I will assist with the pull request.

You don't need to know Hebrew, all you have to do is change the Hebrew strings to the French one while keeping the surrounding quotes (Poedit will do it for you).

If you need any further assistance don't hesitate to reply here.

**Comment by mneiger** [comment]
Thanks for the guidance Yaron.
Here is the translated file using Gtranslator.

[fr.po.txt](https://github.com/hebcal/hebcal/files/2485221/fr.po.txt)

**Comment by yarons** [comment]
Sure, the error messages are required, the reason these are not translated in Hebrew is that the terminal does not support Right-To-Left and sometimes the text is reversed.

There's no such problem with French so feel free to translate these and thanks in advance!

**Comment by mneiger** [comment]
Hi Yaron,
Here it is with the error messages.
Is there any reason for Tu B'Shvat to be mentioned twice ? 

[fr.po.txt](https://github.com/hebcal/hebcal/files/2488575/fr.po.txt)

**Comment by yarons** [comment]
@mneiger, no clue, you might want to open an additional issue about that.

**Comment by mjradwin** [comment]
This will be released in Hebcal 4.15

**Comment by yarons** [comment]
Do I need to create the strings_fr file myself?
I see that this commit broke the build.

**Comment by mjradwin** [comment]
This was released as part of c0a4b6a8e917c45554972966d82e83b2a202f8ab and v4.15
