### ISSUE TITLE
Print Mode: Candle Lighting / Shabbat Ending

### ISSUE THREAD

**Issue by ajbitton** [hebcal/hebcal#159]
Thank you for creating such a great tool for people to use!

I would love a simple print-friendly version just like "Candle-lighting Times" but with the Shabbat ending times. Making it nice and simple.

I printed the calendar out but it seems too late for the tiny amount of information needed. This way I can print a nice little 1 pager to hang.

Just a thought.

Thanks in advance!!!

**Comment by mjradwin** [comment]
Thanks for this suggestion. We're working on this feature and getting ready to release it.

You can append `&havdalah=1` to our Fridge shabbat times page. So if the URL from the website is this:

https://www.hebcal.com/shabbat/fridge.cgi?zip=02906&b=18&M=off&m=42&lg=s&year=5782

Then you can get Havdalah times like this:

https://www.hebcal.com/shabbat/fridge.cgi?zip=02906&b=18&M=off&m=42&lg=s&year=5782&havdalah=1

Please take a look and tell us what you think!

**Comment by ajbitton** [comment]
This looks great! Looks like I need to hack it a bit in the url to adjust location and times. My feedback is as follows (if your not working on it already):

1. Print mode (choose what you want printed, ex: removing the the "← 5781" "5783 →"  I don't think that needs to be printed)
2. Easily edit the location, times - like you do on your main page: https://www.hebcal.com/hebcal?v=0&maj=on&min=on&nx=on&mf=on&ss=on&mod=on&o=on&s=on&i=off&year=2018&yt=G&lg=s&c=on&geo=zip&zip=90048&b=18&m=30. I assume it will show up once you release this though.
3. Perhaps some aesthetic options to give some character to the print out - for example: to add a border around it - a few simple options, to personalize it.

I hope that helps. Looking forward to seeing the final product. Keep up the great work!
