### ISSUE TITLE
Hebrew date without punctuation

### ISSUE THREAD

**Issue by riva-dev** [hebcal/hebcal#164]
Can you add a field that contains the Hebrew date with no punctuation?
Thanks!

**Comment by mjradwin** [comment]
We added a `heDateParts` field when `category` == `hebdate` to the [Jewish calendar REST API](https://www.hebcal.com/home/195/jewish-calendar-rest-api).

For example:

```json
{
  "title": "14th of Av",
  "date": "2022-08-11",
  "hdate": "14 Av 5782",
  "category": "hebdate",
  "title_orig": "14 Av 5782",
  "hebrew": "י״ד אב",
  "heDateParts": {
    "y": "תשפ״ב",
    "m": "אב",
    "d": "י״ד"
  }
}
```

`heDateParts` is also available via the [Hebrew Date Converter REST API](https://www.hebcal.com/home/219/hebrew-date-converter-rest-api).
