### ISSUE TITLE
hebcal command line -H with month

### ISSUE THREAD

**Issue by shayaknyc** [hebcal/hebcal#172]
Hey, couldn't find documentation on this. Currently in linux self-compiled version 4.16. 
$ hebcal -H 5779

This spits out all of the 5779 calendar in gregorian. However, if I type:
$ hebcal -H 5779 Adar

It just shows me the command-line options.

If I type:
$ hebcal -H 5779 06

I get the error:
"hebcal: Don't use number to specify Hebrew months."

So, how do I pass a Hebrew calendar date and have it convert to Gregorian on command-line? It seems I can only do that from Gregorian to Hebrew?

**Comment by dsadinoff** [comment]
hebcal -H adar 5779

I was in America when I wrote it, so it's always [month [day]] year
:)

**Comment by dsadinoff** [comment]
adar_1 for אדר ראשון

**Comment by shayaknyc** [comment]
Ah! Thank you! Possible to have it spit out ALL gregorian dates provided Hebrew Year and Month? Not just dates with Chagim?

**Comment by dsadinoff** [comment]
hebcal -dH adar_1 5779
hebcal -dH adar_2 5779
hebcal -dH adar 5779

**Comment by shayaknyc** [comment]
🤦‍♂️ duh! Sorry! Thanks.....
