### ISSUE TITLE
Hungarian localisation

### ISSUE THREAD

**Issue by MendySK** [hebcal/hebcal#174]
I wish to localise the calendar to Hungarian. I downloaded the Hebrew version, and am working on the translation. I hope you can help me with submitting it.
Thanks

**Comment by dsadinoff** [comment]
That's great!  happy to help.

**Comment by OlegKorchickiy** [comment]
Hello, 

me and @MendySK working on the application that will really benefit if hebcal will get Hungarian localisation, since it is our primary app language.

here is the translated file, hope it is suitable for you.

[HebCal Hungarian.txt](https://github.com/hebcal/hebcal/files/3047578/HebCal.Hungarian.txt)

**Comment by OlegKorchickiy** [comment]
Thanks for help @mjradwin !

When you plan to update hebcal.com api?

We use https://www.hebcal.com/home/195/jewish-calendar-rest-api and it is important for us to have Hungarian translation there.

I tried `lg=hu` but it not up to date yet.

```
{
    "error": "Sorry, invalid language <strong>hu</strong>."
}
```

**Comment by mjradwin** [comment]
It could be another week. I'd like to include this and #169 in a release and then it will get deployed to hebcal.com

**Comment by OlegKorchickiy** [comment]
Ok thanks!

**Comment by mjradwin** [comment]
Released in hebcal 4.17

**Comment by OlegKorchickiy** [comment]
@mjradwin thanks for help! But we got one more issue, as i noticed all titles are translated, but memo not, please take a look at the attached screenshot.

![Screenshot 2019-05-03 at 14 59 57](https://user-images.githubusercontent.com/4789347/57139100-9b62e000-6db4-11e9-8927-81ca285a9682.png)

Can you tell us what file we should take to translate all the memos?

Thank you!

**Comment by mjradwin** [comment]
Hi, we don't yet have a way to translate memo text; only event titles are currently supported in our translation file.
