### ISSUE TITLE
Torah readings for holidays through the API?

### ISSUE THREAD

**Issue by dotkas** [hebcal/hebcal#176]
Hello.

I am able to find Torah readings for holidays on the [hebcal.com website](https://www.hebcal.com/holidays/rosh-hashana), however, I cannot seem to get it through the developer API.

The [Developer API](https://www.hebcal.com/home/195/jewish-calendar-rest-api) is able to give me either **dates** for holidays, or **readings** for Saturdays.

Am I missing something?

**Comment by mjradwin** [comment]
You're not missing anything. These aren't yet exposed through the API. There is a similar issue posted here:

https://github.com/hebcal/dotcom/issues/16

As an interim workaround, you can download CSV files for the next 10 years here:

https://www.hebcal.com/sedrot/#download

**Comment by dotkas** [comment]
Closing due to duplicate. Thanks 👍
