### ISSUE TITLE
REST API - location parameter not working

### ISSUE THREAD

**Issue by ilibilibom** [hebcal/hebcal#179]
On the API calls, 
It seems that the location parameter is returning the same result with the i=on/off parameter. 
Here is a example: 
http://www.hebcal.com/converter/?cfg=json&hy=5779&hm=Tamuz&hd=4&h2g=1&i=on
And
http://www.hebcal.com/converter/?cfg=json&hy=5779&hm=Tamuz&hd=4&h2g=1&i=off
Are returning the same result. 
Can someone hep with understanding the issue here ?

**Comment by mjradwin** [comment]
The Hebrew Date converter API doesn't (yet) support an i=on/off parameter.
It's never been a feature of the API.

https://www.hebcal.com/home/219/hebrew-date-converter-rest-api

**Comment by ilibilibom** [comment]
> The Hebrew Date converter API doesn't (yet) support an i=on/off parameter. It's never been a feature of the API. https://www.hebcal.com/home/219/hebrew-date-converter-rest-api

Got it! Thanks
