### ISSUE TITLE
Yahrzeit Dates Wrong #2

### ISSUE THREAD

**Issue by scatmanFATMAN** [hebcal/hebcal#180]
Hi,

If you use the following link to generate a yahrzeit for 10 years, the first date is before the current time and actually spits back 11 dates.

https://www.hebcal.com/yahrzeit/?t=Yahrzeit&years=10&y1=2010&m1=4&d1=10

![yahrzeit](https://user-images.githubusercontent.com/7003050/61836235-50a1b300-ae4d-11e9-8cb2-ae82e432c407.png)

**Comment by mjradwin** [comment]
Thanks for the bug report. This is now fixed.
