### ISSUE TITLE
Parashot looks wrong

### ISSUE THREAD

**Issue by ishahak** [hebcal/hebcal#181]
Hi, thank you for this wonderful service.

It looks like there is a bug in the Parashot computations.

for today:
curl "https://www.hebcal.com/converter/?cfg=json&i=on&g2h=1&gy=2019&gm=7&gd=25"
{"gy":2019,"gm":7,"gd":25,"hy":5779,"hm":"Tamuz","hd":22,"hebrew":"\u05db\u05f4\u05d1 \u05d1\u05bc\u05b0\u05ea\u05b7\u05de\u05bc\u05d5\u05bc\u05d6 \u05ea\u05e9\u05e2\u05f4\u05d8","events":["**Parashat Pinchas**"]}
>> It should be Matot.

Also if checking for coming Sunday:
curl "https://www.hebcal.com/converter/?cfg=json&i=on&g2h=1&gy=2019&gm=7&gd=28"
{"gy":2019,"gm":7,"gd":28,"hy":5779,"hm":"Tamuz","hd":25,"hebrew":"\u05db\u05f4\u05d4 \u05d1\u05bc\u05b0\u05ea\u05b7\u05de\u05bc\u05d5\u05bc\u05d6 \u05ea\u05e9\u05e2\u05f4\u05d8","events":["Parashat **Matot-Masei**"]}
>>It should be separated!

Thank you!

**Comment by mjradwin** [comment]
The Hebrew date converter API does not currently support `i=on` or `i=off` parameter. It currently only provides events for Diaspora.
