### ISSUE TITLE
Yahrtzeit display failing

### ISSUE THREAD

**Issue by cpjhenry** [hebcal/hebcal#183]
Running version 4.18 on GNU bash, version 5.0.11

My sister passed away on December 25th, 1999, however, hebcal isn't displaying her yahrtzeit date.

In testing, hebcal appears to not display for Gregorian dates between December 13th and January 10th inclusive. I have three names in my yahrtzeit file; I have moved these around, reduced to one, etc. with no effect.

I have not started to look at the code, assuming it should be an easy error to find for someone familiar with the code.

**Comment by mjradwin** [comment]
This is not a bug; Hebcal is behaving correctly. 25 December 1999 = 16th of Tevet, 5760

The 16th of Tevet sometimes occurs in December and sometimes occurs in January.

Here's a demo to show you that the yahrzeit is being calculated correctly.

```
$ cat yahrzeit.txt
12 25 1999 Person1
$ ./hebcal --years 10 -h -x -Y yahrzeit.txt
1/13/2020 Person1
12/31/2020 Person1
12/20/2021 Person1
1/9/2023 Person1
12/28/2023 Person1
1/16/2025 Person1
1/5/2026 Person1
12/26/2026 Person1
1/15/2028 Person1
$ 

```
