### ISSUE TITLE
Times are wrong for Rio de Janeiro 

### ISSUE THREAD

**Issue by feinstein** [hebcal/hebcal#185]
When I create a new calendar the times show fine, but when I import them to my Google Calendar on Android, the times are wrong, 1 hour behind.

This year Brazil removed daylight saving time, it might related with that.

**Comment by mjradwin** [comment]
Thanks for the bug report. We will work on fixing this issue.

**Comment by mjradwin** [comment]
OK - we identified the source of the problem and have deployed a fix, but it might take 1-7 days for Google Calendar on Android to refresh our calendar feed.
