### ISSUE TITLE
Sometimes the Hebcal API sends a truncated response

### ISSUE THREAD

**Issue by Arrow7000** [hebcal/hebcal#186]
When sending requests to the API I sometimes get a `Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING` error in Chrome. Also making requests with Postman sometimes fails completely and other times returns a truncated JSON response.

I've been using this link which triggers the faulty response sometimes: https://www.hebcal.com/hebcal/?v=1&cfg=json&maj=on&min=off&mod=off&nx=off&year=now&month=x&ss=off&mf=off&c=on&geo=pos&m=0&s=off&latitude=-37.868748599999996&longitude=144.9973363&tzid=Australia/Sydney

Chrome:
![image](https://user-images.githubusercontent.com/13225609/70994033-675ce500-2121-11ea-9bd2-29fdb04c2986.png)

Postman:
![image](https://user-images.githubusercontent.com/13225609/70994549-9cb60280-2122-11ea-97e5-375970bf6eac.png)

**Comment by Arrow7000** [comment]
Here's one example where I managed to catch it in action. As you can see the JSON is just cleanly truncated.

![image](https://user-images.githubusercontent.com/13225609/71178252-e2f59800-22c1-11ea-84aa-ccf0e80711a8.png)

Zoomed in view of the response:

![image](https://user-images.githubusercontent.com/13225609/71178299-fe60a300-22c1-11ea-9093-9f7e2168bb46.png)

**Comment by mjradwin** [comment]
During the past year we've made some big changes to the hebcal.com website. The entire set of APIs are now generated by Node.js instead of Perl + C code. I'm closing this bug as it's likely no longer relevant.
