### ISSUE TITLE
segmentation fault  - null city

### ISSUE THREAD

**Issue by ShaiHoresh** [hebcal/hebcal#187]
when I'm trying to get sunrise-and-sunset times, I get segmentation fault.
I saw you had a similar problem in big endian systems - mine is little endian... 

$ ./hebcal -T --sunrise-and-sunset
25th of Tevet, 5780
Segmentation fault (core dumped)

**Comment by dsadinoff** [comment]
Hello ShaiHoresh, 
can you provide the output from `hebcal info`, 
as well as anything else about the environment, including `uname -a`, the distribution, etc.

thanks.

**Comment by ShaiHoresh** [comment]
info:
hebcal version 4.19
timezone_db version 2019.2

Environment variable for default city: HEBCAL_CITY

Environment variable for default options: HEBCAL_OPTS

running on ubuntu 18.04 on lenovo G50-70
4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

BUT!!! I tried it also on another PC, and got the same segmentation fault as well..

**Comment by dsadinoff** [comment]
Looks like your version of hebcal wasn't compiled with a default city, which I think constitutes a build error, but one we should handle more gracefully.

in the meantime, try 
`hebcal -TO  --city new_york `
or some value from 
`hebcal cities`

or specify lattitude and longitude.

**Comment by ShaiHoresh** [comment]
Okay, with --city Jerusalem it doesn't fail.
I ran `./configure --with-default-city="Jerusalem"`
and then `./hebcal -TO`, and I got again a segmentation fault

**Comment by dsadinoff** [comment]
...and `hebcal info`?

**Comment by ShaiHoresh** [comment]
same same...

**Comment by dsadinoff** [comment]
...so that's the bug.  okay, well, you've got a workaround for now using --city or -L -l.

I've modified the Issue name to reflect the diagnosis.  I'll try to have a look at the configuration bug at some point soon.

**Comment by mjradwin** [comment]
Fixed on `master`.
