### ISSUE TITLE
Shabbat Candle Times Event on Google Calendar should include the End time

### ISSUE THREAD

**Issue by feinstein** [hebcal/hebcal#188]
The Shabat Candle times only have the start time as `18:14 to 18:14`, it should include the minutes defined on the calendar creation e.g. for 18 minutes: `18:14 to 18:32` as it was the old behavior some years ago.

**Comment by mjradwin** [comment]
Thanks for the suggestion. We made the change to keep the event a 0-minute duration a few years ago after some consideration. It's a simpler and clearer experience to have the current experience. It's also consistent with how we treat Havdalah times, and how we will plan to treat other z'manim in the future.

**Comment by feinstein** [comment]
@mjradwin any chance I could get this as an additional optional configuration?
