### ISSUE TITLE
Hebrew date format broken

### ISSUE THREAD

**Issue by pinecone460** [hebcal/hebcal#191]
I'm running hebcal 4.19 on Ubuntu Studio 20.04 from the official Ubuntu repos.

The output of the command:
`hebcal -tH`

produces:
5/14/5780 13th of Iyyar, 9540
5/14/5780 28th day of the Omer

It seems that the following things are true:
 - The month and day in the condensed date are in gregorian format
 - The year in the non-condensed date is in "super-Hebrew" format (Gregorian plus 3760 times two)

**Comment by dsadinoff** [comment]
Confirmed.  I don't have an ETA for a fix, but this is a real combination-of-arguments bug that I'm surprised we haven't seen before.

**Comment by mjradwin** [comment]
Thanks for the bug report! Fixed in 4.20
