### ISSUE TITLE
4.20 Fails With "Multiple Definition of "hebcal_languages" in translations.h

### ISSUE THREAD

**Issue by snakeroot** [hebcal/hebcal#192]
Attempting to build new release fails with the following:

gcc -DHAVE_CONFIG_H -I.  -DVERSION='"4.20"' -DHAVE_STDLIB_H -DHAVE_STRING_H -DHAVE_INTTYPES_H   -g -O2 -c -o translations.o translations.c
gcc  -g -O2   -o hebcal common.o danlib.o error.o greg.o hebcal.o timelib.o astro.o tm2unixtime.o unixtime2tm.o dow.o parse_tz.o holidays.o sedra.o start.o gnu.o dafyomi.o strings_ashkenazi.o strings_he.o strings_pl.o strings_ru.o strings_fi.o strings_fr.o strings_hu.o strings_ashkenazi_litvish.o strings_ashkenazi_poylish.o strings_ashkenazi_standard.o translations.o   -lm
/usr/bin/ld: hebcal.o:/home/chris/build/hebcal_build/420/hebcal-4.20/translations.h:10: multiple definition of `hebcal_langs'; common.o:/home/chris/build/hebcal_build/420/hebcal-4.20/translations.h:10: first defined here
/usr/bin/ld: holidays.o:/home/chris/build/hebcal_build/420/hebcal-4.20/translations.h:10: multiple definition of `hebcal_langs'; common.o:/home/chris/build/hebcal_build/420/hebcal-4.20/translations.h:10: first defined here
/usr/bin/ld: sedra.o:/home/chris/build/hebcal_build/420/hebcal-4.20/translations.h:10: multiple definition of `hebcal_langs'; common.o:/home/chris/build/hebcal_build/420/hebcal-4.20/translations.h:10: first defined here
/usr/bin/ld: start.o:/home/chris/build/hebcal_build/420/hebcal-4.20/translations.h:10: multiple definition of `hebcal_langs'; common.o:/home/chris/build/hebcal_build/420/hebcal-4.20/translations.h:10: first defined here
/usr/bin/ld: dafyomi.o:/home/chris/build/hebcal_build/420/hebcal-4.20/translations.h:10: multiple definition of `hebcal_langs'; common.o:/home/chris/build/hebcal_build/420/hebcal-4.20/translations.h:10: first defined here
/usr/bin/ld: translations.o:/home/chris/build/hebcal_build/420/hebcal-4.20/translations.h:10: multiple definition of `hebcal_langs'; common.o:/home/chris/build/hebcal_build/420/hebcal-4.20/translations.h:10: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:498: hebcal] Error 1
make[2]: Leaving directory '/home/chris/build/hebcal_build/420/hebcal-4.20'
make[1]: *** [Makefile:560: all-recursive] Error 1
make[1]: Leaving directory '/home/chris/build/hebcal_build/420/hebcal-4.20'
make: *** [Makefile:399: all] Error 2

LMK if there's additional info I can provide.

**Comment by mjradwin** [comment]
Thanks for the bug report. That's a really strange error. What kind of
build environment are you using?

We've tested Hebcal builds on various Linux (Debian, Ubuntu) and Mac. You
can see from Travis that it's building fine with both gcc and clang.

https://travis-ci.org/github/hebcal/hebcal/builds/687038853

You'll find other recommendations about required build environment in the
README.md here:

https://github.com/hebcal/hebcal/blob/master/README.md#build--install

**Comment by mjradwin** [comment]
Fixed on `master` branch.

**Comment by snakeroot** [comment]
Now builds with no errors. Thanks!
