### ISSUE TITLE
Too many aliyot for Shabbat Rosh Chodesh Chanukah

### ISSUE THREAD

**Issue by ezrag26** [hebcal/hebcal#197]
Currently, an additional (8th) Aliya is added to the readings to accommodate the additional reading of Rosh Chodesh before Maftir. According to the Shulchan Aruch (684:3) (https://en.wikisource.org/wiki/Translation:Shulchan_Aruch/Orach_Chaim/684):

> If the New Moon of [the month of] Tevet falls out on the Sabbath, we take out three [Torah] scrolls, and six [honorees] read from the weekly portion, and in the second [scroll] one [honoree] reads from [the portion of] the New Moon, and he begins from "And on the Sabbath day…," [‍Numbers 28:9–15] and in the third the maftir is read from [the portion of] Hanukkah

This would mean there should still be 7, not 8, Aliyot before Maftir

**Comment by mjradwin** [comment]
Update: CSV files on hebcal.com have been regenerated to show 7 aliyot + maftir. Google Drive spreadsheets still show 8 aliyot + maftir.

**Comment by mjradwin** [comment]
We've updated Google Drive spreadsheets as well. Closing this issue.
