### ISSUE TITLE
Unable to download birthdays calendar

### ISSUE THREAD

**Issue by shloimicohen** [hebcal/hebcal#198]
Hi there,

I am unable to download birthdays calendar. Once all dates are entered it won’t let me subscribe or download the calendar. When trying for to download the yearly calendar I have no issues just the customised birthday etc. can you assist?

Thank you!

**Comment by mjradwin** [comment]
Thank you for the bug report and our sincere apologies for the inconvenience.

The error was introduced due to a server software upgrade, and it has since been fixed.

Please try your download again.
