### ISSUE TITLE
Jewish calendar REST API problem

### ISSUE THREAD

**Issue by rt400** [hebcal/hebcal#200]
Hi,
before i get data by take Sunday date and Saturday date and i get the data of full week, i see now that he missing the havdalah times. 
any idea ?

**Comment by mjradwin** [comment]
Could you post some code here and example output?

**Comment by rt400** [comment]
> Could you post some code here and example output?

this is the link that i used : https://www.hebcal.com/hebcal/?v=1&cfg=fc&start=2020-09-11&end=2020-09-12&ss=on&c=on&geo=pos&latitude=32.1168092&longitude=35.1158249&tzid=Asia/Jerusalem&m=40&s=on

and the result : 
`[{"title":"Candle lighting","start":"2020-09-11T18:32:00+03:00","allDay":false,"className":"candles","hebrew":"הדלקת נרות"}]`

there is no "Havdalah" times...

**Comment by mjradwin** [comment]
Thanks - this was helpful! Indeed, you discovered a bug, and we have fixed it now.

With that URL you should now get this result:

```json
[{"title":"Candle lighting","start":"2020-09-11T18:32:00+03:00","allDay":false,"className":"candles","hebrew":"הדלקת נרות"},
{"title":"Parashat Nitzavim-Vayeilech","start":"2020-09-12","allDay":true,"className":"parashat","hebrew":"פרשת נצבים־וילך","url":"https://www.hebcal.com/sedrot/nitzavim-vayeilech-20200912?i=on&utm_source=js&utm_medium=fc","description":"Torah: Deuteronomy 29:9-31:30\nHaftarah: Isaiah 61:10 - 63:9"},
{"title":"Havdalah (40 min)","start":"2020-09-12T19:29:00+03:00","allDay":false,"className":"havdalah","hebrew":"הבדלה"}]
```
