### ISSUE TITLE
Chanukah Candle-lighting Time Difference in Jerusalem

### ISSUE THREAD

**Issue by mooioom** [hebcal/hebcal#204]
bsd

I'm attaching the image :

The hebcal website about Jerusalem 1st Chanuka candle time

**Chanukah: 1 Candle: 17:15 on Thursday, 10 December 2020**

...

This is about 20 minutes after the median Israeli calendars, and about 13 minutes after the latest one (Chabad), this is critical because of couple of things :

2. The more important issue - Shabbat, if there is really a time difference of 20 minutes, the user the feeling that it's not Shabbat WHILE SHABBAT HAS ENTERED ABOUT 20 MINUTES BEFORE WHICH IS CAUSING HILUL SHABBAT!!!!

1. The time for Chanuka candle lighting is about 30 minutes after "Tset Hakochavim" if there is a time difference of 20 minutes it's a big difference from the other calendars (will attach some)

Here are some other calendars found here in Israel, all created by Talmidei Chachamim in Yeshivot in Israel for the times of "Tset Hakochavim" in Jerusalem (1st Candle of Chanuka)

1. Or Hachaim - 16:54 - 21 minutes difference
2. Kotel Website - 17:00
3. Hazon Shamayim - 16:55
4. R' Eitan Tsikoni - 16:48
5. R' Zalman Melamed - 16:53
6. Chabad is the latest found with 17:02

But none of them with 17:15 (!!!)

This is a serious bug which should be fixed ASAP

<img width="380" alt="lj5dxw6uaC" src="https://user-images.githubusercontent.com/7930742/101286433-2c046c00-37f3-11eb-8291-b9031a141337.png">

**Comment by mjradwin** [comment]
Hi, thanks so much for using Hebcal and for filing a ticket.

On Friday and Saturday nights, Hebcal Chanukah candle-lighting times always match the user's preference for Shabbat times. On Friday, this is 40 minutes before sundown in Jerusalem, and defaults to 18 minutes (overridable by the end user) for cities outside of Jerusalem.

On Saturday night, Chanukah candle-lighting times match the user's preference for Havdalah. This is either Tzeit haKochavim (defined conservatively by Hebcal as solar depression of 8.5 degrees for 3 small stars) or a fixed number of minutes past sundown (typical values being 42 minutes past sundown for 3 medium stars, 50 minutes for 3 small stars, or 72 minutes for Rabbeinu Tam).

There are different minhagim on when to light Chanukah candles on outside of Friday & Shabbat. Some sources say to light Chanukah candles at sunset (shkia). Some say to light when the first star is visible, which can vary by location 15-20 minutes after sunset. Some say to light at Tzeit haKochavim (which again, can be defined several different ways - including solar depression of 7.083 degrees for 3 medium-sized stars, or 8.5 degrees for 3 small stars).

Therefore, to address a point you made in your bug report, I don't see any issues with Shabbat. Hebcal's implementation of Chanukah candle-lighting times is very careful to avoid any violation of Shabbat both on Friday and Saturday. I see no need to make any changes for Friday or Saturday.

I hope the above explains the current behavior of Hebcal and Chanukah candle-lighting times.

Now, to proceed for non-Shabbat and the different minhagim, we can do a few things:

1. Leave things alone - the Tzeit haKochavim 8.5 degrees implementation is what exists today, and has been working well for most users for the past several years.

2. Adjust Chanukah candle-lighting times for non-Friday and non-Saturday to be another time

2a. Pick sunset (shkia) as the the time

2b. Pick Tzeit haKochavim 7.083 degrees as the time (approx 10 minutes earlier than current times)

2c. Give the user a choice between sunset, 7.083 degrees, 8.5 degrees, or fixed number of minutes past sundown (leading to a lot of flexibility but a very complicated UI for the hebcal.com website)
