### ISSUE TITLE
Option for Year in Hebrew Numerals

### ISSUE THREAD

**Issue by markhdavid** [hebcal/hebcal#206]
Currently, there's an option to show the hebrew year. But it only shows the year in Arabic numerals (e.g., 5729). Please have an option at least to show this in Hebrew numerals (e.g., תשכ"ט).

**Comment by mjradwin** [comment]
Confirming that you're looking for this feature on the hebcal command-line interface using the `-8` option?

```
$ ./hebcal -8 -t
1/2/2021 18th of טֵבֵת, 5781$ 
```

The website already displays Hebrew year in Hebrew numerals if you select the Hebrew language option, e.g.

https://www.hebcal.com/hebcal?v=1&i=off&year=2021&yt=G&lg=h&d=on&c=off&geo=none

**Comment by yisraeldov** [comment]
Also with the `--lang he` option

**Comment by mjradwin** [comment]
Fixed in hebcal v4.24

**Comment by yisraeldov** [comment]
@mjradwin GREAT! Thanks!
