### ISSUE TITLE
Shabbat Mevarchim

### ISSUE THREAD

**Issue by nkasimer** [hebcal/hebcal#207]
The date converter shows whether a day is Shabbat Mevarchim.  It'd be nice to have that in the REST APIs, with info about what day(s) next week are Rosh Chodesh, and maybe the molad announcement.

**Comment by mjradwin** [comment]
An excellent suggestion.

We've enabled this feature for the REST API if *both* Special Shabbat are enabled (`ss=on`) and Rosh Chodesh is enabled (`nx=on`). For example:

https://www.hebcal.com/hebcal?v=1&cfg=json&nh=on&nx=on&ss=on&start=2021-02-01&end=2021-02-28

Will include this `item`:

```json
{
  "title": "Shabbat Mevarchim Chodesh Adar",
  "date": "2021-02-06",
  "category": "mevarchim",
  "hebrew": "שבת מברכים חודש אדר",
  "memo": "Molad Adar: Fri, 19 minutes and 4 chalakim after 6:00"
}
```
