### ISSUE TITLE
Sunrise/sunset changes by large amount between February and March

### ISSUE THREAD

**Issue by sdubois** [hebcal/hebcal#213]
I am noticing a very large change in the time for sunrise (and sunset) between 02-28 and 03-01. This seems to be true in every calendar year, which leads me to believe there is a bug somewhere in the Hebcal code that is causing this. My hunch is that February only having 28 (or 29) days might have something to do with it.

For example, if we look at sunrise in 07666 for 2021-02-28 (https://www.hebcal.com/zmanim?cfg=json&start=2021-02-28&geo=zip&zip=07666) it is 06:36, but for 2021-03-01 (https://www.hebcal.com/zmanim?cfg=json&start=2021-03-01&geo=zip&zip=07666) it is 06:30. That's a difference of 6 minutes in just one day, whereas the differences between the previous day (2021-02-27) is 1 minute and subsequent day (2021-03-02) is only 2 minutes. 

I brought this up to @nkasimer who created a spreadsheet of the change in sunrise times for 999 days in 07666 starting from 2021-01-01. As you can see, the changes correspond nicely with the seasons and are usually only a couple of minutes, but the difference between 02-28 and 03-01 in any year is always 6 six minutes, an obvious outlier. 

Here is a link to that spreadsheet and a screenshot of the chart.

https://docs.google.com/spreadsheets/d/1OpQTPeeG1oyb29XctjGekoZE3OVjv7gvykPVcJC7mYw/edit?usp=sharing

![image](https://user-images.githubusercontent.com/479460/109556983-1bcff600-7a9d-11eb-8754-0e42e13f2600.png)

**Comment by nkasimer** [comment]
To add some additional data--I compared a year's worth of sunrise times from hebcal and the Python zmanim library.  For most of the year there's fairly consistent error, which I assume is attributable to a combination of rounding, slightly different locations, refractions models, etc.  But throughout Jan and Feb the difference increases significantly over time, falling abruptly to a fairly consistent level March through December.  The y axis is difference in sunrise times in minutes.

![image](https://user-images.githubusercontent.com/60622473/109564000-1d51ec00-7aa6-11eb-8243-df5c101e4d0f.png)

**Comment by sdubois** [comment]
Digging a little deeper, I calculated sunrise times using the solar-calc nodejs package (https://www.npmjs.com/package/solar-calc) that the Hebcal Zmanim API is using and it appears that this is where the problem is coming from.

Attached is a text file and corresponding chart of the sunrise times for the same date range and location as above, which shows the gradual drift in January and February followed by a significant drop off on March 1. 

Thanks to @nkasimer for the chart!

[solarcalc_sunrise_teaneck.txt](https://github.com/hebcal/hebcal/files/6064921/solarcalc_sunrise_teaneck.txt)

![image](https://user-images.githubusercontent.com/479460/109569775-981f0500-7aae-11eb-8478-c66530383146.png)

**Comment by sdubois** [comment]
I tested the hebcal command line program and this problem does not appear to occur. 

Since this issue is actually on hebcal-es6, I've opened a new ticket there. https://github.com/hebcal/hebcal-es6/issues/22

Feel free to close this ticket, but the screenshots and information provided here will be useful in getting to the bottom of this issue.

**Comment by mjradwin** [comment]
Thanks again! Fixed in https://github.com/hebcal/hebcal-es6/issues/22
