### ISSUE TITLE
Adding German translations to hebcal

### ISSUE THREAD

**Issue by olivermaor** [hebcal/hebcal#217]
Translations into German which follow the common conventions for transliteration in liturgical context:

- The softly spoken "ב" and the "ו" spoken as a consonant both transliterate to "w", e.g. "**W**ajikra".
- The "י" transliterates to "j" if pronounced as a consonant, while "i" when pronounced as a vocal, e.g.: "Wa**j**ikra".
- The "ב" at the end of a word is transliterated "w", e.g. "Jom To**w**".
- Except for "Jom haSikaron", the modern rememberance days are translated to "... - Tag", while "Aliyah" is not translated, as no one in the community calls "Aliyah" other than "Aliyah" (it is also not called "immigration day", "elevation day" or "return day" or anything like that in English).

I found that some locations with Jewish communities of considerable size in German speaking countries are missing, so I will add them in a different pull request which is to follow.

The pull request includes
- an added "po" file for "de", which is the ISO code for the German language,
- a required change to the Makefile,
- "de" also added in the README, and
- a suggestion for an update in the NEWS.

I tested the installation in a virtual box under Linux Mint, and it compiles without errors.

**Comment by mjradwin** [comment]
Thanks for sending the pull request! We'll get this released shortly.

**Comment by mjradwin** [comment]
Oh, I see you're also adding some cities. I'll hold off on the release until you've wrapped that up.

**Comment by olivermaor** [comment]
Thank you, and good to hear all this, and that you are going to quickly add the additions. The cities are "delivered" now, as well.

**Comment by mjradwin** [comment]
Released in v.25
