### ISSUE TITLE
Add cities in the German speaking area to list

### ISSUE THREAD

**Issue by olivermaor** [hebcal/hebcal#219]
In #217 and #218 , the addition of German translation had been discussed / proposed in form of a pull request.
Within this context, it makes sense to add some more "cities" coverage for German speaking areas. It is a matter of taste what cities to add, and I chose to add rather more than rather less places, as I do not see that there is any inherent limit to the cities.h file.

Therefore, I will make a pull request, adding cities with larger Jewish communities or of importance for international travel. Concerning the sizes of the communities, it might be worthwhile to know that only about half of the Jews actually living in Germany are registered members of a Jewish community, as the mandatory religious tax which the communities are permitted to levy from their members discourage many from registration.
In particular:

- **Basle**: estimated 1,000 members; second largest community in German speaking part of Switzerland.
- **Bozen**: German speaking part of Italy; Bolzano in Italian; capital of the German speaking South Tyrol / Alto Adige region of Italy.
- **Dresden**: Considerable Jewish community in the capital of the German state of Saxony.
- **Düsseldorf** (called Dusseldorf in the file for compatibility reasons), capital of the German state of North Rhine-Westphalia: Third largest Jewish community in Germany with 7,000 registered members; major trade hub with numerous headquarters of international enterprises.
- **Frankfurt**: One of the largest German Jewish communities (more than 6,300 members); major airport and travel hub (sole flight destination in Europe from Israel during the Covid-19 air traffic lockdown of Israel in 2021); important financial centre (seat of the European Central Bank and some of the largest banks of Europe).
- **Hamburg**: Important port (one of Europe's largest seaports); largest Jewish community in Northern Germany with around 2,600 members.
- **Leipzig**: Largest East German city after Berlin; largest Jewish community in Saxony (1,300 members).
- **Munich**: Second largest Jewish community (after Berlin) with estimated 10,000 members; in the capital of Bavaria; major airport as traffic hub; home of several multinational companies (BMW, Munich Re, Allianz, etc.).
- **Salzburg**: Added to have at least two Austrian cities in it. Larger tourism hub.
- **Vienna**: Major seat of United Nations institutions; seat of the OSCE; large and vivid Jewish community with estimated 7,000 members; capital of Austria.

**Comment by mjradwin** [comment]
Released in v.25
