### ISSUE TITLE
Jewish Calendar API to query only Rosh Chodesh

### ISSUE THREAD

**Issue by mchesler613** [hebcal/hebcal#223]
I'm trying to obtain only Rosh Chodesh dates for a particular month with the calendar api: e.g.
```
https://www.hebcal.com/hebcal?v=1&cfg=json&nx=on&year=now&month=5&geo=zip&zip=08002
```
but it returns nothing:
```
{"title":"Hebcal Diaspora 2021","date":"2021-05-04T17:39:26.555Z","location":{"geo":"none"},"items":[]}
```
If I add `maj=on` to the query, then it returns the major holidays of the month plus Rosh Chodesh.  Is there a way to obtain only Rosh Chodesh info for a particular month without the major holidays?

Thank you,
Merilyn

**Comment by mjradwin** [comment]
Hi, thanks for using Hebcal APIs.

You have indeed discovered a deficiency in our API. Our best recommendation is to add `maj=on` to the query, and then filter the `items` array looking for an item with `category` of `roshchodesh`

**Comment by mchesler613** [comment]
Thanks!
