### ISSUE TITLE
Date for "Pesach Sheni" is off by few weeks

### ISSUE THREAD

**Issue by dmagician038** [hebcal/hebcal#224]
@dsadinoff / @mjradwin, Hi.

I've recently noticed the the date for "_Pesach Sheni_" seems wrong.
It occurs **AFTER "Yom HaAtzma'ut"** instead of **_AFTER "Pesach VIII"_** (tested only for 2020 and 2021 -- guessing it's the same for any year)...

The same bug exist in:
[HebCal site](https://www.hebcal.com/) site **_and_** Command line version [over GIT](https://github.com/hebcal/hebcal).

Attached screenshot of resulting JSON from the published [HebCal API](https://www.hebcal.com/home/help).

![image](https://user-images.githubusercontent.com/1897534/122059074-eef9e180-cdf4-11eb-87ac-9d4f5328396e.png)

Found another bug:
"Ta'anit Esther" and "Erev Purim" _are on the same date_:

![image](https://user-images.githubusercontent.com/1897534/122066352-5adf4880-cdfb-11eb-8b8b-4dfbee59fb04.png)

    Thanks ahead,
               D.

**Comment by mjradwin** [comment]
Pesach Sheni is always on 14 Iyyar, which is exactly one month after Pesach (15 Nisan).

Holiday | Starts | Ends | Hebrew Dates
-- | -- | -- | --
Pesach 2020 | Wed, Apr 8 | Thu, Apr 16 | 15-22 Nisan 5780
Pesach Sheni 2020| Thu, May 7 | Fri, May 8 | 14 Iyyar 5780
Yom HaAtzma'ut 2020 | Tue, Apr 28 | Wed, Apr 29 | 5 Iyyar 5780
Pesach 2021 | Sat, Mar 27 | Sun, Apr 4 | 15-22 Nisan 5781
Pesach Sheni 2021| Sun, Apr 25 | Mon, Apr 26 | 14 Iyyar 5781
Yom HaAtzma'ut 2021 | Wed, Apr 14 | Thu, Apr 15 | 3 Iyyar 5781

Although Yom HaAtzma'ut is normally observed on the 5th of Iyyar, it may be moved earlier or postponed if observance of the holiday (or Yom HaZikaron, which always precedes it) would conflict with Shabbat.

The dates on hebcal.com and via the CLI are correct.

**Comment by mjradwin** [comment]
It's also correct. Ta'anit Esther occurs the day before Purim.
