### ISSUE TITLE
off-by-one-day for Israel DST transition on zmanim API

### ISSUE THREAD

**Issue by dsadinoff** [hebcal/hebcal#228]
consider https://www.hebcal.com/zmanim?cfg=json&tz=Asia%2FJerusalem&geonameid=293807&date=2021-03-26
The output seems to change over from +02:00 to +03:00

but unfortunately the timezone change this spring is on 25th march, not on 26th.

The changeover happens early Friday morning, not Saturday morning (which decidedly wouldn't work)

**Comment by dsadinoff** [comment]
never mind, my year was off, looks fine for 2022.
https://www.hebcal.com/zmanim?cfg=json&Asia/Jerusalem&geonameid=293807&date=2022-03-25

**Comment by mjradwin** [comment]
Phew!
