### ISSUE TITLE
Thare is no heb date in Hebrew 

### ISSUE THREAD

**Issue by tim6400** [hebcal/hebcal#238]
For example this url: https://www.hebcal.com/hebcal?v=1&start=2022-10-05&end=2022-10-05&lg=he&cfg=json&maj=on

It return the Yom kipur without the date in hebrew like this: י׳ תִשְׁרֵי תשפ"ג
I did found this options "D=on" but it's not return the date in the same item of the event.

So why not return the full date in hebrew as well or at least add it as optional paramter by request?

**Comment by mjradwin** [comment]
Hi, thanks for the issue report.

We have added an option `&hdp=1` to include the `heDateParts` field on untimed (all-day) items.

https://www.hebcal.com/hebcal?v=1&start=2022-10-05&end=2022-10-05&lg=he&cfg=json&maj=on&leyning=off&hdp=1

```json
{
  "title": "Hebcal Diaspora October 2022",
  "date": "2022-10-13T21:45:07.595Z",
  "location": {
    "geo": "none"
  },
  "range": {
    "start": "2022-10-05",
    "end": "2022-10-05"
  },
  "items": [
    {
      "title": "יוֹם כִּפּוּר",
      "date": "2022-10-05",
      "hdate": "10 Tishrei 5783",
      "category": "holiday",
      "subcat": "major",
      "yomtov": true,
      "title_orig": "Yom Kippur",
      "hebrew": "יום כפור",
      "link": "https://hebcal.com/h/yom-kippur-2022?us=js&um=api",
      "heDateParts": {
        "y": "תשפ״ג",
        "m": "תשרי",
        "d": "י׳"
      },
      "memo": "Day of Atonement"
    }
  ]
}
```
