### ISSUE TITLE
is there c library for hebcal? 

### ISSUE THREAD

**Issue by emaayan** [hebcal/hebcal#240]
hi..
i'm trying to make an arduino calender similar to this one:
https://www.instructables.com/Hebrew-calendar-date-and-time-with-thermometer-on-/
or this one:
https://www.hackster.io/1040tax/hebrew-alarm-clock-1f8d95
in an attempt to re-create this device (which no longer seems to be available) : 
http://www.jewishsoftware.net/judaica/hebrew-watches/the-jewish-desk-clock.html

natrually one of the hardest things is to actually fine a library that coverts a regular date into jewish ones. 
i found one called hebdate, but i would need to add all the holidays and other times to it. 
i'm wondering if you have such a library in c.

**Comment by mjradwin** [comment]
Hi, thanks for contacting us.

There is a C command-line interface (not a library). It is not designed to be used in a library context (global variables, places where the code calls die() or exit()) but you are welcome to take a look. 

To find the older C code, go back in the GitHub repository to the latest 4.x release 

https://github.com/hebcal/hebcal/tree/v4.31
