### ISSUE TITLE
Transliterated Hebrew output with --lang=he

### ISSUE THREAD

**Issue by lechner** [hebcal/hebcal#241]
Hi,

I packaged Hebcal for Guix, but it may not be working properly. Should the Hebrew output with `--lang=he` still contain some transliterated entries?

Thanks, and please have a good week!

Felix Lechner
```
$ hebcal -E -Z -l 37,33 -L 121,59 -z America/Los_Angeles -S --lang=he 11 20 2022
11/20/2022 כ״ו חֶשְׁוָן תשפ״ג
11/20/2022 פָּרָשַׁת תּוֹלְדוֹת
11/20/2022 Alot haShachar: 05:31
11/20/2022 Misheyakir: 05:55
11/20/2022 Misheyakir Machmir: 06:02
11/20/2022 Dawn: 06:25
11/20/2022 Sunrise: 06:53
11/20/2022 Kriat Shema, sof zeman: 09:23
11/20/2022 Kriat Shema, sof zeman (MGA): 08:47
11/20/2022 Tefilah, sof zeman: 10:13
11/20/2022 Tefilah, sof zeman (MGA): 09:49
11/20/2022 Chatzot hayom: 11:53
11/20/2022 Mincha Gedolah: 12:18
11/20/2022 Mincha Ketanah: 14:49
11/20/2022 Plag HaMincha: 15:51
11/20/2022 Sunset: 16:54
11/20/2022 Dusk: 17:22
11/20/2022 Tzait HaKochavim: 17:35
```

**Comment by mjradwin** [comment]
Thanks for the bug report. It looks like we didn't implement Hebrew translations for the daily Zemanim. We will get this fixed in the next release.

**Comment by mjradwin** [comment]
Hi @lechner, do you have a suggestion for the best single-word Hebrew translations for "dawn" and "dusk", in the civil sense of the terms?

https://www.timeanddate.com/astronomy/civil-twilight.html

Note that I'm not looking for translations of halachic terms like alot haShachar, shkiah, tzeit haKochavim, etc. -- those are already done. I'm looking for the modern Hebrew colloquial (or scientific) terms used for when the sun is 6 degrees below the horizon.

**Comment by lechner** [comment]
Hi @mjradwin, thanks for asking! I live in California.

A good work for "dawn" is probably שחר. To avoid the halachic term, הזריחה (daybreak) may be even better.

I am less sure about "dusk." The traditional word may be שקיעה, yet בין הערביים strikes me more modern and more colloquial. Google prefers חשכה, but to me that sounds darker than civil twilight, which your link described as the "brightest" of the popular measures.

Does the Hebrew [Wikipedia page for "Twilight"](https://he.wikipedia.org/wiki/%D7%93%D7%9E%D7%93%D7%95%D7%9E%D7%99%D7%9D) help? It shows this [image of the three measures](https://he.wikipedia.org/wiki/%D7%93%D7%9E%D7%93%D7%95%D7%9E%D7%99%D7%9D#/media/%D7%A7%D7%95%D7%91%D7%A5:Types-of-twilight-HE.svg).

Either way, it would be best to ask someone who speaks modern Hebrew. I'll be on the lookout for native speakers over Thanksgiving (or maybe next Shabbat)!

**Comment by mjradwin** [comment]
OK, this is now fixed. Got some feedback from a native Hebrew speaker.

```
$ ./hebcal --version
Hebcal version 5.4.3
$ ./hebcal -Z -t --lang=he
11/22/2022 כ״ח חֶשְׁוָן תשפ״ג
11/22/2022 עֲלוֹת הַשַּׁחַר: 5:25
11/22/2022 משיכיר - זמן ציצית ותפילין: 5:50
11/22/2022 משיכיר - זמן ציצית ותפילין: 5:57
11/22/2022 דִּימְדּוּמֵי בּוֹקֵר: 6:21
11/22/2022 הַנֵץ הַחַמָּה: 6:51
11/22/2022 סוֹף זְמַן קְרִיאַת שְׁמַע גר״א: 9:16
11/22/2022 סוֹף זְמַן קְרִיאַת שְׁמַע מג״א: 8:40
11/22/2022 סוֹף זְמַן תְּפִלָּה גר״א: 10:05
11/22/2022 סוֹף זְמַן תְּפִלָּה מג״א: 9:41
11/22/2022 חֲצוֹת הַיּוֹם: 11:42
11/22/2022 מִנְחָה גְּדוֹלָה: 12:06
11/22/2022 מִנְחָה קְטַנָּה: 2:32
11/22/2022 פְּלַג הַמִּנְחָה: 3:32
11/22/2022 שְׁקִיעָה: 4:33
11/22/2022 דִּימְדּוּמֵי עֶרֶב: 5:03
11/22/2022 צֵאת כוכבים: 5:17
$
```

**Comment by mjradwin** [comment]
Fixed another mistranslation with Misheyakir and Misheyakir Machmir in 5.4.4

```
$ ./hebcal -Z -t --lang=he | grep ' 5:5'
11/22/2022 מִשֶּׁיַּכִּיר: 5:50
11/22/2022 מִשֶּׁיַּכִּיר מַחמִיר: 5:57
$
```
