### ISSUE TITLE
Setting defaultCity at build time

### ISSUE THREAD

**Issue by dcjud** [hebcal/hebcal#244]
(preliminary question: is the c/ directory now just an archive?)

It seems `defaultCity` is set in main.go. If one wants to change this at build time, does one edit main.go, or is there a way to set the variable in the build commands?

I ask because I'm updating the Slackbuild script and the latter is preferable to editing main.go from the script.

Up to version 4.31 it was straightforward with `./configure --with-default-city=...` 
Is there something analogous in current version?

In any event, it would be useful to document this ... I would have done so and submitted a pull request, if I understood what needed to be said :)

**Comment by mjradwin** [comment]
Thanks for your question.

We could add support for setting a different default city at build time in an upcoming release. Since there is no longer a `configure` script, it would probably need to be done with the Makefile, perhaps something like `make DEFAULT_CITY="Los Angeles" all`

Would that work?

**Comment by mjradwin** [comment]
And to answer the other questions:

1. The reason setting the default city isn't documented anywhere is that it wasn't clear to the maintainers that this feature was being used. Your question indicates that at least someone found it useful.

2. Yes, the `c` subdirectory is just an archive at this point. It should be removed at some point in the future as anyone needing to peruse the historical 4.x version of the code can just use the git tags.

**Comment by dcjud** [comment]
First: ` make DEFAULT_CITY="Los Angeles" all` ... yes, something like that would be just the ticket!

But I didn't stop to think whether compiling in a different default city was really useful ... truth is, I just did it because there was a `configure` option for it so it seemed like something that should be done. So I suppose it could be dropped in favor of the runtime option or environment variable.

Related to this, it would be useful to see the city printed out whenever relevant, I guess mainly with -c. Just to make it more difficult to read off times for the wrong city. Perhaps `hebcal info` or `hebcal cities` could be made to indicate what city one is looking at.

**Comment by mjradwin** [comment]
Fixed in 5.7.2
