### ISSUE TITLE
hebcal 5.7.2: "make clean all" fails

### ISSUE THREAD

**Issue by dcjud** [hebcal/hebcal#247]
5.7.2 compilation issue.
Running GNU make 4.3 and go 1.16.5 / gcc 11.2.0

```
bash:~/hebcal-5.7.2: make clean all
go clean
echo "package main" > dcity.go
echo "var defaultCity = \""New York"\"" >> dcity.go
sed -e 's/@VERSION@/5.7.2/' hebcal.1.in > hebcal.1
go build -o hebcal
rm -f hebcal
rm -f hebcal.1
rm -f dcity.go
# github.com/hebcal/hebcal
go1: fatal error: cannot open ./dcity.go: No such file or directory
compilation terminated.
make: *** [Makefile:10: hebcal] Error 2
```
However, "make clean" followed by "make all" builds hebcal successfully. Also, "make clean all" works in 5.7.0 and 5.7.1

Looking at the Makefile, it seems like "make clean all" should build dcity.go before attempting to make hebcal so I'm baffled. Maybe something to do with go ... I wouldn't know.

If the solution is simply to update README.md to change "make clean all" to "make clean" then "make all" that would be OK but maybe it's worth understanding why "make clean all" fails. (I sure would like to know :)

BTW building with DEFAULT_CITY= argument seems to work. I compared "DEFAULT_CITY=Boston" to "=DETROIT" and got the expected candlelighting time shift. Thanks for that.

r/
JM

**Comment by mjradwin** [comment]
We can't reproduce your error. I don't understand how your invocation of `make clean all` is causing this error. From the output you pasted, it appears somehow that the `clean` and `all` rules are running in parallel? That doesn't make any sense.

```root@ubuntu-s-1vcpu-1gb-nyc3-01:~/hebcal# make clean all
go clean
rm -f hebcal
rm -f hebcal.1
rm -f dcity.go
echo "package main" > dcity.go
echo "var defaultCity = \""New York"\"" >> dcity.go
go build -o hebcal
sed -e 's/@VERSION@/5.7.2/' hebcal.1.in > hebcal.1
root@ubuntu-s-1vcpu-1gb-nyc3-01:~/hebcal# ./hebcal  --version
Hebcal version 5.7.2
root@ubuntu-s-1vcpu-1gb-nyc3-01:~/hebcal# go version
go version go1.19.5 linux/amd64
root@ubuntu-s-1vcpu-1gb-nyc3-01:~/hebcal# make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
root@ubuntu-s-1vcpu-1gb-nyc3-01:~/hebcal# 
```

**Comment by dcjud** [comment]
I know, right? Doesn't make any sense at all! But you nailed the problem: Some time ago I added MAKEFLAGS=-j2 to my ~/.bashrc, don't remember why. Unset that and everything works as advertised. Guess I'll take that line back out.
Thanks!
