### ISSUE TITLE
Hebrew date without nekudos

### ISSUE THREAD

**Issue by elifine** [hebcal/hebcal#248]
I'm currently using <script src="https://www.hebcal.com/etc/hdate-he.js"></script> to display the current hebrew date on my website. The problem is, that it displays the hebrew date with nekudos and i dont want that.
How can i display today's hebrew date, without nekudos?

**Comment by mjradwin** [comment]
Thanks for the suggestion. We'll endeavor to add this in the coming weeks.

**Comment by mjradwin** [comment]
Hebrew date without nikud was fixed a couple of months ago

```html
<script src="https://www.hebcal.com/etc/hdate-he-v2.js">
</script>
```

https://github.com/hebcal/hebcal-web/commit/fa3b968ee3c250c9d2529e756a9f285c2967e07e
