### ISSUE TITLE
Json shabbos time 

### ISSUE THREAD

**Issue by meyer59** [hebcal/hebcal#249]
Hey
is there any way to have this [output](https://www.hebcal.com/shabbat?cfg=i2&geonameid=5110302&b=18&M=on&lg=ah&tgt=_top) but as json ? Currently it seeems only html is supported. 
This is exactly what we need but as json to fit in our app.
Also Hebrew translation doesn't seems to work on it (lg=ah)
Found it on the original page [here](https://www.hebcal.com/link?geonameid=5110302&b=18&M=on&lg=ah)
Thank you for your great work

**Comment by mjradwin** [comment]
Hi, thanks for using Hebcal APIs!

Yes, you can use our [Shabbat times REST API](https://www.hebcal.com/home/197/shabbat-times-rest-api) to get JSON.

It's very similar to our full [Jewish calendar REST API](https://www.hebcal.com/home/195/jewish-calendar-rest-api). The major difference is that the Shabbat times REST API returns just this week’s Shabbat times and Torah Portion. 

To simulate `lg=ah`, you'll want to use `lg=a`. When you render your results, just concatenate both the `title` and `hebrew` fields from each item in the `items` array.
