### ISSUE TITLE
Accept ISO dates as input

### ISSUE THREAD

**Issue by hectormonacci** [hebcal/hebcal#250]
For the rest of the world, giving hebcal input in USA format (month, day, year) is unnatural.

Example: `hebcal 2 13 1987`.

Please think of offering an option to input dates in ISO format.

Example: `hebcal 1987-02-13`

Since hebcal already offers output in ISO format (-g switch), it would be just natural for it to accept ISO as input format.

**Comment by mjradwin** [comment]
Excellent suggestion!

**Comment by mjradwin** [comment]
Fixed in 5.8.0.

Shabbat shalom!

**Comment by hectormonacci** [comment]
Great news, thank you Mike and Shabbat Shalom!
