### ISSUE TITLE
Hebcal/core npm wrong date

### ISSUE THREAD

**Issue by emethmipo** [hebcal/hebcal#252]
I am using the package hebcal/core but i have an issue. All the dates are wrong converting them from gregorian to jewish dates.

**Comment by mjradwin** [comment]
We are sorry to hear you are having some difficulty using the `@hebcal/core` npm package. 

Please post code examples so we can advise you on how to use the API to get the correct date conversions (and possibly improve our documentation).

**Comment by mjradwin** [comment]
Note also that you'll find some API examples of how to use `HDate` here in the documentation:

https://github.com/hebcal/hebcal-es6/blob/main/README.md#HDate

**Comment by mjradwin** [comment]
Hi @emethmipo , since we didn't hear back from you in over a month, we are going to assume that you figured out your issue.
