### ISSUE TITLE
Cannot build go version

### ISSUE THREAD

**Issue by mondul** [hebcal/hebcal#255]
When I run `go build .` I get:

```
# github.com/hebcal/hebcal
./main.go:323:43: undefined: defaultCity
./main.go:383:38: undefined: defaultCity
```

I can't find where this variable is being declared, please fix

**Comment by mjradwin** [comment]
To build hebcal from the source repository, you'll need the following:

* Go version 1.13 or higher
* GNU make v3.79 or later

Once you have those, you can prepare the build environment as follows:

`make clean all`
