### ISSUE TITLE
Error on adding to Google Calendar

### ISSUE THREAD

**Issue by feinstein** [hebcal/hebcal#257]
I tried to create a new calendar and add it to my Google Calendar on my phone, but I get an error saying "Calendar no longer exists".

**Comment by mjradwin** [comment]
Please follow our Google Calendar instructions on a laptop/desktop browser that is logged into the same Google account you will use on your mobile device

https://www.hebcal.com/home/60/google-calendar-jewish-holidays

The "Calendar no longer exists" error message seems to appear only when trying to subscribe on a mobile device.

**Comment by feinstein** [comment]
So it would be useful to add a warning in the download page, if a mobile
device is detected.
