### ISSUE TITLE
Ha'azinu

### ISSUE THREAD

**Issue by shirafischer** [hebcal/hebcal#259]
The Ha is not a prefix so please lowercase the second A.

**Comment by mjradwin** [comment]
Fixed in hebcal 5.8.2

**Comment by shirafischer** [comment]
Thank you!!!

**Comment by dsadinoff** [comment]
When I started listing all my sins this year, I didn't anticipate spelling among them.

**Comment by dsadinoff** [comment]
> Fixed in hebcal 5.8.2

thanks MJR

**Comment by shirafischer** [comment]
Ha! G'mar tov.
