### ISSUE TITLE
Yahrzeit: First Date in Calendar is in the Past

### ISSUE THREAD

**Issue by scatmanFATMAN** [hebcal/hebcal#260]
Today is 2023-09-10 and when I do a yahrzeit calendar for 10 days, the first date is 2022-12-01 which is in the past.

![criteria](https://github.com/hebcal/hebcal/assets/7003050/ce416c4f-1dc2-470b-8d71-5bec72e65047)
![criteria](https://github.com/hebcal/hebcal/assets/7003050/db314788-4f18-48a9-833c-2fa0aea3488b)

**Comment by mjradwin** [comment]
This is by design. The Yahrzeit calendar calculates anniversaries for the current Hebrew year and up to N (in your case 10) years into the future. Since the current Hebrew year (5783) began on Sunday September 25, 2022, this is the expected result.

**Comment by scatmanFATMAN** [comment]
Ah, thank you. Can close this then.
