### ISSUE TITLE
problem with year dates for portions at the bottom of each Torah portion

### ISSUE THREAD

**Issue by aliamichaels** [hebcal/hebcal#262]
I was just updating a web-based table for 5784 & 5785 and it looks like the end of Deutoromy is incorrect. If nothing else, it looks like 5784 is showing 2023 years. BUT, in particular, can someone verify the dates for 

Ha’azinu 
5784 · [23 Sep 2023]
5785 · [5 Oct 2024]
5786 · [4 Oct 2025]

Vezot Haberakhah
5784 · [8 Oct 2023]
5785 · [25 Oct 2024]
5786 · [15 Oct 2025]

**Comment by mjradwin** [comment]
Thanks for using Hebcal. Why do you think these dates are in error? These dates are correct. We just read Ha'azinu in shul last Shabbat (Shabbat Shuva) and we will read Vezot Haberakhah on Simchat Torah, coming up in a little over a week.
