### ISSUE TITLE
"Update Calendar" button changes are not persisting

### ISSUE THREAD

**Issue by tziporaziegler** [hebcal/hebcal#264]
Steps to repro:

1. Create a new Yahrzeit dates, Hebrew Birthdays, and Hebrew Anniversaries personal calendar with multiple elements
2. Press "Create Calendar"
3. Navigate to the calendar's edit page
4. Press the "Delete" button for one or more form elements
5. Press "Update Calendar"

The list on top of the page updates and it seems like the update completed successfully. However, when I reload the edit page or if I try adding the calendar to Google Calendar, the old events reappear the calendar reverts to all values from when it was originally created.

Browser: Google Chrome
OS: macOS

**Comment by mjradwin** [comment]
Thanks for this error report. We have confirmed this defect on Hebcal.com yahrzeit page and have fixed the error

https://github.com/hebcal/hebcal-web/commit/10990615ec40b6e801537bca84e0745e53ac43ad

Our sincere apologies for any inconvenience
