### ISSUE TITLE
Printing candle lighting times with -C option

### ISSUE THREAD

**Issue by MaxBGreenberg** [hebcal/hebcal#266]
If I use the -C (uppercase) option on a Friday or Saturday, hebcal returns the Hebrew date and candle lighting or havdala time for the specified location.  I noticed this issue on version 5.8.3.

**Comment by mjradwin** [comment]
This is working as desired. Specifying `-C` is intended to enable candle-lighting and fast times, even if `-c` is not explicitly specified.

Here is the relevant excerpt from the README:

#### Options related to candle-lighting times
Option | Description
--- | ---
   -c, --candlelighting | Print candlelighting times.
   -C, --city city | Set latitude, longitude, and timezone according to specified city. This option implies the -c option.
