### ISSUE TITLE
Showing many israeli cities with incorrect flag or not as part of israel

### ISSUE THREAD

**Issue by jamesbien** [hebcal/hebcal#269]
![Screenshot_20240209_111840_Chrome](https://github.com/hebcal/hebcal/assets/34220571/db98099a-5f05-4222-bfa3-62dcbd4275dd)

**Comment by mjradwin** [comment]
Thanks for the bug report. We'll investigate.

**Comment by mjradwin** [comment]
Thanks. We have fixed the underlying issue. There's a 24-hour client-side cache on the results, so to see the updated results today, may need to open an incognito/private browser window and you'll see the correct results from the autocomplete
