### ISSUE TITLE
Unable to access website: hebcal.com

### ISSUE THREAD

**Issue by sephardicu** [hebcal/hebcal#271]
I've been trying to access hebcal.com website for the past 2 day unsuccessfully. I'm using the same chrome browser as I always do. I've tried both https://hebcal.com/ and http.

When I run the Microsoft diagnostics, I get an error stating: "Your DNS server might be unavailable."  I've reset chrome settings and cleared cache. 

![hebcal](https://github.com/hebcal/hebcal/assets/168201218/823b263b-db55-4c8d-b5a7-ab9ee145014a)

**Comment by mjradwin** [comment]
Thanks for the bug report, and we are terribly sorry for the inconvenience. We are working to restore access to the website. The issue is with DNS, and was caused by the switch from Google Domains to Squarespace Domains. The DNSSEC records were configured improperly, and the Squarespace Domains website is giving errors when trying to correct the misconfiguration. We've been trying to get in touch with Squarespace Customer Support for over 24 hours now and they are being unresponsive. We will update you as soon as we have a resolution, hopefully before the end of Pesach.

**Comment by haimskira** [comment]
It also affects the integration in Home Assistant

![Screenshot 2024-04-26 181440](https://github.com/hebcal/hebcal/assets/117645982/369eb2c8-7c42-4edd-9b75-50ef31e2859f)

**Comment by sephardicu** [comment]
@mjradwin No apology needed. Thank you for the quick response - just wanted to eliminate the possiblility of an issue on our end. Wishing your site refuah shelema! 

@haimskira - very cool setup. Is that Google's Assistant?

**Comment by haimskira** [comment]
> @mjradwin No apology needed. Thank you for the quick response - just wanted to eliminate the possiblility of an issue on our end. Wishing your site refuah shelema!
> 
> @haimskira - very cool setup. Is that Google's Assistant?

Home assistant 😃

**Comment by mjradwin** [comment]
Update - Squarespace Domains was unable to resolve the DNSSEC issue - there is indeed a serious problem in their system. They have escalated internally and promise resolution within one business day. We don't work on Shabbat, so we'll check back in on Saturday night and hope to have good news by then.

**Comment by legacy370** [comment]
As of 2:25 pm EDT, I find that hebcal.com does not access the site, but www.hebcal.com does.  This is the same for Firefox, Chrome, and Opera, accessing from an iPhone.  On my Linux machine, I got past the problem yesterday, by editing my /etc/hosts file, to include
45.55.96.251    hebcal.com
45.55.96.251    www.hebcal.com

**Comment by mjradwin** [comment]
Squarespace Customer Support finally got back to us, and we have disabled the incorrect DNSSEC, we appear to have a resolution. 

   Domain Name: HEBCAL.COM
   Registry Domain ID: 46523722_DOMAIN_COM-VRSN
   Registrar: Squarespace Domains II LLC
   Name Server: NS1.DIGITALOCEAN.COM
   Name Server: NS2.DIGITALOCEAN.COM
   Name Server: NS3.DIGITALOCEAN.COM
   DNSSEC: unsigned

It could take another 24-72 hours (approximately) for DNS caches across the Internet to reset.

**Comment by mjradwin** [comment]
This issue should be resolved. Let us know if you are still having problems accessing the website? Again, our apologies for the outage and Mo'adim L'simcha!
