### ISSUE TITLE
Hebrew without nikud option

### ISSUE THREAD

**Issue by akivazev** [hebcal/hebcal#275]
Would it be possible to add a language option of Hebrew without nikud? I'd be happy to work on a pull request if somebody could explain to me what needs to be done.

**Comment by mjradwin** [comment]
To confirm, you are looking for Hebrew without nikud for the CLI? Or for the Hebcal.com website and web apis?

**Comment by akivazev** [comment]
I am personally interested in the CLI though it would be worthwhile to work on it for the website and web APIs.

**Comment by mjradwin** [comment]
The website and APIs already support language `he-x-NoNikud`

https://www.hebcal.com/home/4534/jewish-calendar-event-language-support

We can look into adding this support to the CLI.

**Comment by mjradwin** [comment]
Fixed in 5.8.7

Try `hebcal --lang=he-x-NoNikud`
