### ISSUE TITLE
Incorrect weekly sedra displayed near Rosh Hashana

### ISSUE THREAD

**Issue by mjradwin** [hebcal/hebcal#29]
Submitted by gzaz on 2005-10-11 01:59:42

I noticed a bug with the weekly sedra feature last year
and forgot about it until it cropped up again during
the same time a year later.  When "hebcal -hS'" is run
on a day in the beginning of the week just before Rosh
Hashana, it incorrectly shows "Parashat Bereshit".

**Comment by acli** [comment]
Is this bug still present in hebcal 4.6? I tried to force it to reproduce but it doesn’t seem to be reproducible.

Am I correct that the only place hebcal gets the current date from the system is setDate() in greg.c?

**Comment by mjradwin** [comment]
Yes, I think this issue got fixed sometime on or around f9212a3b52f67a991713fc78371e413d7644c7ba.
