### ISSUE TITLE
Making an Israeli version

### ISSUE THREAD

**Issue by mjradwin** [hebcal/hebcal#37]
Submitted by mradwin on 2001-12-24 12:31:51

1) it's passively developed :) I have a steadily 
growing list of things to
do, and patches.  I hope to leverage the sourceforge 
site for letting other
people play.  Patches are welcome

2)  gettext sounds like overkill, but a legitimate 
possibility.   The output
is already pretty table-driven, so I don't think that 
adding another output
style would be all that complex; no need to resort to 
a different paradigm
entirely.  But if you feel strongly about this 
implmeentation zei gezunt.  I
do so enjoy the prospect of having ashkenazis and 
sepharadit hebrew being
assigned different ISO localization codes. :)

3) No, there is currently no support for the israeli 
holiday scheme.  By
rights, the -i "israeli parshiot" mode ought to do 
this but doesn't.  It
would require an augmentation of the holiday data 
structures to represent
this cleanly, or just apply a (slightly) different 
table for the Israeli
case.

-----Original Message-----
From: Gavrie Philipson [mailto:gavrie@philipson.co.il]
Sent: Sat, December 22, 2001 1:35 PM
To: Danny Sadinoff
Subject: hebcal: Making an Israeli version

Hi Danny,

First of all, let me thank you for hebcal. I've been 
using it for quite
a while, and like it very much.

However, there are some changed I'd like to make for a 
project I'm
doing. A few questions:

1. Is hebcal still being actively developed or is it 
dormant? Do you
still maintain it?

2. I'd like to translate hebcal to use Hebrew 
character (i.e. not
English transliteration). As I don't see any 
preparation of
localization, I thought of using GNU gettext. Any 
comments?

3. Finally, is there some way to have the holidays 
appear according to
the Israeli calendar (only one day instead of two days 
for most
holidays)? If it exists, I must have overlooked it...

Thanks,

Gavrie.

**Comment by catalandres** [comment]
Out of clarity, this is still open because of the request to localize it in Hebrew, right?

**Comment by mjradwin** [comment]
I'm not sure why this is open. Issue #115 is tracking the full localization effort using gettext.
