### ISSUE TITLE
xml/unicode support

### ISSUE THREAD

**Issue by mjradwin** [hebcal/hebcal#53]
Submitted by sadinoff on 2002-09-05 12:01:27

wouldn't it be nice if hebcal could emit xml?  

Utf-8-encoded 
hebrew?

**Comment by mjradwin** [comment]
utf-8 encoded Hebrew is available as of hebcal v4.4 with `--lang he`.

Not planning to add XML at this time.

**Comment by Scimonster** [comment]
FWIW It should be easy to write a thin wrapper around Hebcal-JS to give back XML.
