### ISSUE TITLE
Add daily zmanim for davening, etc.

### ISSUE THREAD

**Issue by mjradwin** [hebcal/hebcal#68]
Submitted by rgottlieb on 2008-08-14 11:15:57

It might be nice to have daily zmanim for davening, etc.

See e.g.:
http://www.geocities.com/hyneni/Download/tmr-zman.txt
http://www.kosherjava.com/zmanim/docs/api/net/sourceforge/zmanim/ZmanimCalendar.html

**Comment by mjradwin** [comment]
This was fixed in #114.

**Comment by dsadinoff** [comment]
I'd like this to be opened until we have a spec and testcases.   I'm marking the feature as experimental until then.

**Comment by mjradwin** [comment]
With the port of Hebcal from C to Golang complete, I'd like to mark this as closed again.

Test cases have been added and times generated by the Hebcal CLI match other sources such as MyZmanim.com typically within one minute.
