### ISSUE TITLE
sunset times appear to be incorrect

### ISSUE THREAD

**Issue by yisraeldov** [hebcal/hebcal#81]
For example today I got 

10/10/2013	Sunrise: 6:41; Sunset: 6:16

but from myzmanim I get sunset at 6:14

http://www.myzmanim.com/day.aspx?vars=27488541/10-10-2013//2/11.5/22////////////338ad6

From the hebcal site I get 

Candle lighting: 5:56pm on Friday, 11 October 2013

add 18 min and it is 6:14

Emacs gives me sunset at 18:13

From the calendar on the wall 18:13

Google gives me 6:13 PM
Sunset in Rehovot, Israel

hebcal is giving 2 or 3 min late!!!

**Comment by mjradwin** [comment]
We merged in new sunset engine in hebcal-4.0. This issue should be fixed now.
