### ISSUE TITLE
Hebrew Calendar in Salesforce

### ISSUE THREAD

**Issue by jrosenbloom77** [hebcal/hebcal#86]
I'm looking for Hebrew calendar functionality for Salesforce.  Have you guys considered building it?  Do you know anyone that has?

**Comment by RebbePod** [comment]
> I'm looking for Hebrew calendar functionality for Salesforce. Have you guys considered building it? Do you know anyone that has?

@jrosenbloom77 Did you ever find a solution?

**Comment by mjradwin** [comment]
It looks like there's an off-the-shelf integration that someone has built specifically for yahrzeits:

https://appexchange.salesforce.com/listingDetail?listingId=a0N3A00000FYjvnUAD&tab=e

There's also a consulting company that offers to do custom Hebcal + Salesforce integrations.

https://www.cloudcreations.com/integration/hebcal-jewish-calendar/
