### ISSUE TITLE
Candle Lighting times are range

### ISSUE THREAD

**Issue by jlasiter** [hebcal/hebcal#92]
it would be preferable to have the start and end times for candle lighting be the same.  i.e. the actual candle lighting time.  Currently it's the full 18 minute range.  so it appears thus in our application:

![screen shot 2014-10-14 at 10 15 21 am](https://cloud.githubusercontent.com/assets/9215703/4630335/a2b52da8-53ac-11e4-8dbd-0c16a3d41852.png)

**Comment by mjradwin** [comment]
After some thorough testing for interoperability, we have adjusted candle lighting times on the hebcal.com iCalendar feeds to be 0 minutes in duration. Thanks for suggesting this.
