### ISSUE TITLE
Candlelighting Missing For 2nd Day of Pesach Outside of Israel

### ISSUE THREAD

**Issue by sabonmichal** [hebcal/hebcal#94]
http://www.hebcal.com/hebcal/?year=2015&month=4&yt=G&v=1&nh=on&i=off&lg=s&vis=on&c=on&geo=zip&zip=90210&b=18&m=72&.cgifields=nx&.cgifields=nh&.cgifields=mf&.cgifields=ss&.s=Create+Calendar

Aren't candles lit for the 2nd day? This calendar, for example, lists a candlelighting for the 2nd day:

http://www.chabad.org/calendar/candlelighting_cdo/aid/6226/jewish/Candle-Lighting-Times.htm#locationId=90210&locationType=2&tdate=4/1/2015

**Comment by mjradwin** [comment]
After many many years, this is fixed in hebcal-4.1. Thanks @aperomsik!

**Comment by sabonmichal** [comment]
thank you!!
