### ISSUE TITLE
Converting IP To Location

### ISSUE THREAD

**Issue by adam105** [hebcal/hebcal#97]
Hi,

This is an elaboration of issue I emailed earlier today to hebcal webmaster:

>>Location can be specified by any of the 200 major cities in the HTML version of our website, or via >>GeoNames id (almost any city worldwide with population of 15000+).

How do we get the GeoNames ID? 

It appears that the hebcal api needs a zipcode so our developer wrote a custom function to convert location to to zip but when he tests it out on his location (Chandigarh, India), it returns the following:

stdClass Object
(
    [error] => Sorry, can't find
16008 in the zip code database.
)

but when I put Chandigarh into the Jewish Holiday interface it recognizes the city and assigns a geoname id: http://www.hebcal.com/hebcal/?year=5775&month=x&yt=H&v=0&nh=on&s=on&i=off&lg=s&vis=on&c=on&geo=geoname&geonameid=1274746&b=18&m=72

The question is, after we establish a user's IP and convert it to a location, how do we then get candlelighting/havdalah times from hebcal api for that location? i.e. how do we convert city name to geoname id?

תודה רבה!

**Comment by mjradwin** [comment]
Closing this as the documentation has been updated to describe the "geo=pos" option.
